### ISSUE TITLE
Error when opening project with uninstalled modules

### ISSUE THREAD

**Issue by Vinai** [enriquepiatti/Magicento#1]
This happens when I open a project with modules in a modman directory that aren't linked into Magento.

```
Error during dispatching of java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.intellij.openapi.util.EdtRunnable$1@11b2864,notifier=n    ull,catchExceptions=false,when=1346750614096] on apple.awt.CToolkit@2fb4b69d
java.lang.NullPointerException
at java.io.File.<init>(File.java:222)
at com.magicento.actions.SetMagePathAction.actionPerformed(SetMagePathAction.java:37)
at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:619)
at com.intellij.ui.popup.AbstractPopup$17.run(AbstractPopup.java:1162)
at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:615)
at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:596)
at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:566)
at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:55)
at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:102)
at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:682)
at java.awt.EventQueue.access$000(EventQueue.java:85)
at java.awt.EventQueue$1.run(EventQueue.java:643)
at java.awt.EventQueue$1.run(EventQueue.java:641)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:652)
at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:699)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:420)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:378)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by enriquepiatti** [comment]
Hi Vinai, are you getting that error when using Alt+M (option+M) > Set Path to Mage.php only? can you set the path to Mage.php from the Settings > Magicento panel?

**Comment by Vinai** [comment]
I can't try that - I can't change the setting any more:
1) open the settings dialog and go to the Magicento panel
2) change the path to Mage.php to the current project
3) click Apply and OK or OK directly
4) open the dialog again
5) the old value still is present

**Comment by enriquepiatti** [comment]
Vinai, what version of Magicento, PHPStorm, and OS are you using?
Also, is this happening with every magento project? for example what happens if you create a new local and clean magento project?
Finally, when you click OK on the settings panel, it doesn't throw any exception?

**Comment by Vinai** [comment]
Versions I am using:
- Magicento 0.6
- PHPStorm 4.0.3
- OS X 10.7.4

When I open a fresh project on a vanilla Magento installation no error happens.

When clicking on the OK button of the settings panel I don't get an exception.

Maybe this helps:
For some projects I keep modules in a separate folder in the Magento root that is called .modman.
The modules live in subdirectories of the .modman directory, for example

.modman/moduleA
.modman/moduleB
...

Then I use the modman script to symlink the files from those directories into the Magento code base to the appropriate directory branches. This serves the purpose of having each module in it's own repository, and enables me to manage the whole site through git and link to specific module revisions via git submodules.

A result of this is that there might be modules in the .modman directory that **are not linked** into the Magento source.
So even though there are PHP files below .modman/moduleA in which `Mage::getModel('moduleA/the_class')` is called, Magento itself can't resolve the class because moduleA isn't deployed into Magento.
Just an idea. Maybe the error is completely unrelated.

**Comment by enriquepiatti** [comment]
mmm... yes maybe that could break some features, I will try to use .modman and see what happens, anyway, it should not break the settings panel. Are the checkboxes saved? the path to php?

**Comment by Vinai** [comment]
In the project I configured the settings for the first time I can change the values (path to Mage.php and/or Checkboxes). When I open another project, changes in the Magicento settings are not saved (neither checkboxes nor the path).

**Comment by enriquepiatti** [comment]
Vinai, I think I don't understand exactly the problem, magicento is working for new projects without .modman? is working for new projects with .modman? is working (all the features) but when you restart the project the settings are cleared? please feel free to add me to skype (enriquepiatti) if you prefer that so we can see the problem together.

**Comment by Vinai** [comment]
Thanks for the Skype call. Just for sake of completeness: the issue is unrelated to undeployed modules in .modman.
The settings can't be changed when multiple projects are open. More specifically, they can't be changed in any but the original project where the setting was created the first time.

**Comment by enriquepiatti** [comment]
Thank you! Vinai for reporting the issue, I will try to fix it in the next release so you can open multiple projects at the same time.
Regards !
