### ISSUE TITLE
Element: class com.intellij.psi.impl.source.xml.XmlTagImpl: Element: class com.intellij.psi.impl.source.xml.XmlTagImpl

### ISSUE THREAD

**Issue by vfranz** [enriquepiatti/Magicento#10]
Element: class com.intellij.psi.impl.source.xml.XmlTagImpl: Element: class com.intellij.psi.impl.source.xml.XmlTagImpl
com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.xml.XmlTagImpl
    at com.intellij.psi.impl.source.tree.CompositePsiElement.getProject(CompositePsiElement.java:295)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.getSubTags(XmlTagImpl.java:638)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.findSubTags(XmlTagImpl.java:660)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.findSubTags(XmlTagImpl.java:655)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.findFirstSubTag(XmlTagImpl.java:674)
    at com.magicento.models.xml.MagentoXmlTag.filterDuplicatedNames(MagentoXmlTag.java:157)
    at com.magicento.models.xml.MagentoXmlTag.getPossibleDefinitions(MagentoXmlTag.java:129)
    at com.magicento.extensions.MagicentoXmlCompletionContributor$2.addCompletions(MagicentoXmlCompletionContributor.java:170)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:156)
    at com.magicento.extensions.MagicentoXmlCompletionContributor.fillCompletionVariants(MagicentoXmlCompletionContributor.java:235)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:110)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:103)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:90)
    at com.intellij.codeInsight.completion.XmlNoVariantsDelegator.fillCompletionVariants(XmlNoVariantsDelegator.java:26)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
    at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:114)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$2$1$1.run(CodeCompletionHandlerBase.java:357)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:918)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$2$1.run(CodeCompletionHandlerBase.java:348)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:181)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:221)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:172)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$2.run(CodeCompletionHandlerBase.java:344)
    at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:457)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:148)

com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.xml.XmlTagImpl
    at com.intellij.psi.impl.source.tree.CompositePsiElement.getProject(CompositePsiElement.java:295)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.getSubTags(XmlTagImpl.java:638)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.findSubTags(XmlTagImpl.java:660)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.findSubTags(XmlTagImpl.java:655)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.findFirstSubTag(XmlTagImpl.java:674)
    at com.magicento.models.xml.MagentoXmlTag.filterDuplicatedNames(MagentoXmlTag.java:157)
    at com.magicento.models.xml.MagentoXmlTag.getPossibleDefinitions(MagentoXmlTag.java:129)
    at com.magicento.extensions.MagicentoXmlCompletionContributor$2.addCompletions(MagicentoXmlCompletionContributor.java:170)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:156)
    at com.magicento.extensions.MagicentoXmlCompletionContributor.fillCompletionVariants(MagicentoXmlCompletionContributor.java:235)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:110)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:103)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:90)
    at com.intellij.codeInsight.completion.XmlNoVariantsDelegator.fillCompletionVariants(XmlNoVariantsDelegator.java:26)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
    at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:114)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$2$1$1.run(CodeCompletionHandlerBase.java:357)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:918)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$2$1.run(CodeCompletionHandlerBase.java:348)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:181)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:221)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:172)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$2.run(CodeCompletionHandlerBase.java:344)
    at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:457)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:148)

com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.xml.XmlTagImpl
    at com.intellij.psi.impl.source.tree.CompositePsiElement.getProject(CompositePsiElement.java:295)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.getSubTags(XmlTagImpl.java:638)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.findSubTags(XmlTagImpl.java:660)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.findSubTags(XmlTagImpl.java:655)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.findFirstSubTag(XmlTagImpl.java:674)
    at com.magicento.models.xml.MagentoXmlTag.filterDuplicatedNames(MagentoXmlTag.java:157)
    at com.magicento.models.xml.MagentoXmlTag.getPossibleDefinitions(MagentoXmlTag.java:129)
    at com.magicento.extensions.MagicentoXmlCompletionContributor$2.addCompletions(MagicentoXmlCompletionContributor.java:170)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:156)
    at com.magicento.extensions.MagicentoXmlCompletionContributor.fillCompletionVariants(MagicentoXmlCompletionContributor.java:235)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:110)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:103)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:90)
    at com.intellij.codeInsight.completion.XmlNoVariantsDelegator.fillCompletionVariants(XmlNoVariantsDelegator.java:26)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
    at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:114)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$2$1$1.run(CodeCompletionHandlerBase.java:357)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:918)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$2$1.run(CodeCompletionHandlerBase.java:348)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:181)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:221)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:172)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$2.run(CodeCompletionHandlerBase.java:344)
    at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:457)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:148)

com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.xml.XmlTagImpl
    at com.intellij.psi.impl.source.tree.CompositePsiElement.getProject(CompositePsiElement.java:295)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.getSubTags(XmlTagImpl.java:638)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.findSubTags(XmlTagImpl.java:660)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.findSubTags(XmlTagImpl.java:655)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.findFirstSubTag(XmlTagImpl.java:674)
    at com.magicento.models.xml.MagentoXmlTag.filterDuplicatedNames(MagentoXmlTag.java:157)
    at com.magicento.models.xml.MagentoXmlTag.getPossibleDefinitions(MagentoXmlTag.java:129)
    at com.magicento.extensions.MagicentoXmlCompletionContributor$2.addCompletions(MagicentoXmlCompletionContributor.java:170)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:156)
    at com.magicento.extensions.MagicentoXmlCompletionContributor.fillCompletionVariants(MagicentoXmlCompletionContributor.java:235)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:110)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:103)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:90)
    at com.intellij.codeInsight.completion.XmlNoVariantsDelegator.fillCompletionVariants(XmlNoVariantsDelegator.java:26)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
    at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:114)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$2$1$1.run(CodeCompletionHandlerBase.java:357)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:918)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$2$1.run(CodeCompletionHandlerBase.java:348)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:181)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:221)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:172)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$2.run(CodeCompletionHandlerBase.java:344)
    at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:457)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:148)

com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.xml.XmlTagImpl
    at com.intellij.psi.impl.source.tree.CompositePsiElement.getProject(CompositePsiElement.java:295)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.getSubTags(XmlTagImpl.java:638)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.findSubTags(XmlTagImpl.java:660)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.findSubTags(XmlTagImpl.java:655)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.findFirstSubTag(XmlTagImpl.java:674)
    at com.magicento.models.xml.MagentoXmlTag.filterDuplicatedNames(MagentoXmlTag.java:157)
    at com.magicento.models.xml.MagentoXmlTag.getPossibleDefinitions(MagentoXmlTag.java:129)
    at com.magicento.extensions.MagicentoXmlCompletionContributor$2.addCompletions(MagicentoXmlCompletionContributor.java:170)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:156)
    at com.magicento.extensions.MagicentoXmlCompletionContributor.fillCompletionVariants(MagicentoXmlCompletionContributor.java:235)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:110)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:103)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:90)
    at com.intellij.codeInsight.completion.XmlNoVariantsDelegator.fillCompletionVariants(XmlNoVariantsDelegator.java:26)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
    at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:114)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$2$1$1.run(CodeCompletionHandlerBase.java:357)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:918)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$2$1.run(CodeCompletionHandlerBase.java:348)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:181)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:221)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:172)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$2.run(CodeCompletionHandlerBase.java:344)
    at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:457)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:148)

**Comment by enriquepiatti** [comment]
I can't reproduce the error vfranz, could you add more information? is this happening in all your magento projects? what OS and PHPStorm version are you using?
