### ISSUE TITLE
StringIndexOutOfBoundsException: String index out of range: -1: String index out of range: -1

### ISSUE THREAD

**Issue by ihor-sviziev** [enriquepiatti/Magicento#119]
In some cases I have next exception, I don't know how I can it reproduce.

```
String index out of range: -1: String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(String.java:1911)
    at com.magicento.extensions.FactoryTypeProvider2.getForeachBySignature(FactoryTypeProvider2.java:314)
    at com.magicento.extensions.FactoryTypeProvider2.getBySignature(FactoryTypeProvider2.java:255)
    at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:379)
    at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:277)
    at com.jetbrains.php.PhpIndexImpl.getClasses(PhpIndexImpl.java:388)
    at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:354)
    at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:277)
    at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:79)
    at com.jetbrains.php.lang.psi.resolve.types.PhpType.globalLocationAware(PhpType.java:378)
    at com.jetbrains.php.lang.inspections.PhpParamsInspection.checkCall(PhpParamsInspection.java:79)
    at com.jetbrains.php.lang.inspections.PhpParamsInspection.access$000(PhpParamsInspection.java:23)
    at com.jetbrains.php.lang.inspections.PhpParamsInspection$1.visitPhpMethodReference(PhpParamsInspection.java:47)
    at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:31)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:74)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$5.process(LocalInspectionsPass.java:380)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$5.process(LocalInspectionsPass.java:375)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:119)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:42)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:82)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:91)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:103)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:79)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

Magicento: 2.6.5
PhpStorm 8 EAP PS-134-1456 (also this issue reproducing in latest stable PhpStorm 7.1.3).

**Comment by enriquepiatti** [comment]
Hi @igor-svizev this and other bugs will be fixed on the next release, I think I will release a minor version today or during the weekend, you will receive the notification. Thanks for reporting it!
