### ISSUE TITLE
Null pointer exception in DB console

### ISSUE THREAD

**Issue by ihor-sviziev** [enriquepiatti/Magicento#120]
![image](https://f.cloud.github.com/assets/1873745/2418726/87810d18-ab4b-11e3-85ec-2f1e0223e700.png)
When you open DB console and try use Alt+M we have next exception:

```
null
java.lang.NullPointerException
    at com.magicento.actions.CopyTemplateAction.isApplicable(CopyTemplateAction.java:33)
    at com.magicento.MagicentoAction._getMagentoContextActions(MagicentoAction.java:112)
    at com.magicento.MagicentoAction.executeAction(MagicentoAction.java:31)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:369)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:493)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

```

Magicento 2.7.0
PhpStorm 8 EAP PS-134.1456

**Comment by enriquepiatti** [comment]
Hi @igor-svizev I cannot reproduce it, please could you test if it's really related with the DB toolwindow? are you sure the cursor is not there? what happens if you have another file opened (and try with just one) what happens if you don't have any file opened?

**Comment by ihor-sviziev** [comment]
@enriquepiatti You click on this icon, than you will have window "Data Source", wait few seconds and then you use ALT+M and have NullPointerException. See screenshot:
![image](https://f.cloud.github.com/assets/1873745/2420497/2a454dfe-ab72-11e3-8fc0-1fd482e03043.png)
PS: AssertionException is in PhpStorm Core module, it's not your issue.

**Comment by enriquepiatti** [comment]
I can reproduce it now, thanks for the clarification!
will be fixed on the next release, for now please don't use ALT+M inside an editor without a "physical" filepath

**Comment by Schrank** [comment]
I have this error too, but without DB window :-)

```
null
java.lang.NullPointerException
at com.magicento.actions.CopyTemplateAction.isApplicable(CopyTemplateAction.java:33)
at com.magicento.MagicentoAction._getMagentoContextActions(MagicentoAction.java:112)
at com.magicento.MagicentoAction.executeAction(MagicentoAction.java:31)
at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:369)
at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:493)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by enriquepiatti** [comment]
@Schrank have you detected when that error occurs? 
tip that nullpointer exception is thrown when Magicento cannot find the virtual file (a real file at really, with a real file path) associated to the current edited file, for example in the case of a DB window it seems there isn't any real file associated with that.
