### ISSUE TITLE
Must not change document outside command or undo-transparent action.

### ISSUE THREAD

**Issue by ihor-sviziev** [enriquepiatti/Magicento#122]
When I created new module, file config.xml isn't formatted(i think it's should be fixed later), when I try to format it I have next exception:

```
Must not change document outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor: Must not change document outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor
com.intellij.util.IncorrectOperationException: Must not change document outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor
    at com.intellij.openapi.editor.impl.DocumentImpl.e(DocumentImpl.java:758)
    at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:731)
    at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:709)
    at com.intellij.openapi.editor.impl.DocumentImpl.deleteString(DocumentImpl.java:519)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.a(PsiToDocumentSynchronizer.java:292)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.access$100(PsiToDocumentSynchronizer.java:37)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer$6.syncDocument(PsiToDocumentSynchronizer.java:264)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer$1.run(PsiToDocumentSynchronizer.java:104)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.performAtomically(PsiToDocumentSynchronizer.java:128)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.a(PsiToDocumentSynchronizer.java:101)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.commitTransaction(PsiToDocumentSynchronizer.java:261)
    at com.intellij.pom.core.impl.PomModelImpl.a(PomModelImpl.java:236)
    at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:195)
    at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:169)
    at com.intellij.psi.impl.source.tree.CompositeElement.replaceChild(CompositeElement.java:695)
    at com.intellij.psi.formatter.FormatterUtil.replaceWhiteSpace(FormatterUtil.java:332)
    at com.intellij.lang.xml.XmlFormattingModel.replaceWithPsiInLeaf(XmlFormattingModel.java:109)
    at com.intellij.psi.formatter.PsiBasedFormattingModel.a(PsiBasedFormattingModel.java:101)
    at com.intellij.psi.formatter.PsiBasedFormattingModel.replaceWhiteSpace(PsiBasedFormattingModel.java:64)
    at com.intellij.formatting.FormatProcessor.a(FormatProcessor.java:389)
    at com.intellij.formatting.FormatProcessor.access$2400(FormatProcessor.java:37)
    at com.intellij.formatting.FormatProcessor$ApplyChangesState.doIteration(FormatProcessor.java:1420)
    at com.intellij.formatting.FormatProcessor$State.iteration(FormatProcessor.java:1246)
    at com.intellij.formatting.FormatProcessor.iteration(FormatProcessor.java:244)
    at com.intellij.formatting.FormatterImpl$MyFormattingTask.iteration(FormatterImpl.java:878)
    at com.intellij.formatting.FormatterImpl.a(FormatterImpl.java:256)
    at com.intellij.formatting.FormatterImpl.format(FormatterImpl.java:206)
    at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.a(CodeFormatterFacade.java:131)
    at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processRange(CodeFormatterFacade.java:95)
    at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processElement(CodeFormatterFacade.java:91)
    at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:104)
    at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:91)
    at com.magicento.actions.CreateModuleAction$1.run(CreateModuleAction.java:229)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:984)
    at com.magicento.actions.CreateModuleAction.reformatFile(CreateModuleAction.java:225)
    at com.magicento.actions.CreateModuleAction.createModuleXmlFile(CreateModuleAction.java:215)
    at com.magicento.actions.CreateModuleAction.executeAction(CreateModuleAction.java:49)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:369)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:733)
    at com.intellij.ui.popup.AbstractPopup$18.run(AbstractPopup.java:1248)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:649)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:630)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:600)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
    at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:108)
    at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

PhpStorm 8 EAP PS-136.1575
OS: Fedora 20

**Comment by enriquepiatti** [comment]
Fixed, will be available with the next release. Anyway, this seems to be happening only in the EAP version.
@igor-svizev send me an email if you want to use a pre-release version with the bugfix for this.
