### ISSUE TITLE
Must not change document outside command or undo-transparent action.

### ISSUE THREAD

**Issue by Schrank** [enriquepiatti/Magicento#124]
PHPStorm 138.184

Must not change document outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor
com.intellij.util.IncorrectOperationException: Must not change document outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor
    at com.intellij.openapi.editor.impl.DocumentImpl.e(DocumentImpl.java:758)
    at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:731)
    at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:709)
    at com.intellij.openapi.editor.impl.DocumentImpl.deleteString(DocumentImpl.java:519)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.a(PsiToDocumentSynchronizer.java:292)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.access$100(PsiToDocumentSynchronizer.java:37)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer$6.syncDocument(PsiToDocumentSynchronizer.java:264)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer$1.run(PsiToDocumentSynchronizer.java:104)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.performAtomically(PsiToDocumentSynchronizer.java:128)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.a(PsiToDocumentSynchronizer.java:101)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.commitTransaction(PsiToDocumentSynchronizer.java:261)
    at com.intellij.pom.core.impl.PomModelImpl.a(PomModelImpl.java:235)
    at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:194)
    at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:169)
    at com.intellij.psi.impl.source.tree.CompositeElement.replaceChild(CompositeElement.java:695)
    at com.intellij.psi.formatter.FormatterUtil.replaceWhiteSpace(FormatterUtil.java:332)
    at com.intellij.lang.xml.XmlFormattingModel.replaceWithPsiInLeaf(XmlFormattingModel.java:109)
    at com.intellij.psi.formatter.PsiBasedFormattingModel.a(PsiBasedFormattingModel.java:101)
    at com.intellij.psi.formatter.PsiBasedFormattingModel.replaceWhiteSpace(PsiBasedFormattingModel.java:64)
    at com.intellij.formatting.FormatProcessor.a(FormatProcessor.java:389)
    at com.intellij.formatting.FormatProcessor.access$2400(FormatProcessor.java:37)
    at com.intellij.formatting.FormatProcessor$ApplyChangesState.doIteration(FormatProcessor.java:1420)
    at com.intellij.formatting.FormatProcessor$State.iteration(FormatProcessor.java:1246)
    at com.intellij.formatting.FormatProcessor.iteration(FormatProcessor.java:244)
    at com.intellij.formatting.FormatterImpl$MyFormattingTask.iteration(FormatterImpl.java:861)
    at com.intellij.formatting.FormatterImpl.a(FormatterImpl.java:253)
    at com.intellij.formatting.FormatterImpl.format(FormatterImpl.java:203)
    at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.a(CodeFormatterFacade.java:131)
    at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processRange(CodeFormatterFacade.java:95)
    at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processElement(CodeFormatterFacade.java:91)
    at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:104)
    at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:91)
    at com.magicento.actions.CreateModuleAction$1.run(CreateModuleAction.java:229)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:984)
    at com.magicento.actions.CreateModuleAction.reformatFile(CreateModuleAction.java:225)
    at com.magicento.actions.CreateModuleAction.createModuleXmlFile(CreateModuleAction.java:215)
    at com.magicento.actions.CreateModuleAction.executeAction(CreateModuleAction.java:49)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:369)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:733)
    at com.intellij.ui.popup.AbstractPopup$18.run(AbstractPopup.java:1250)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:651)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:632)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:602)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
    at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:108)
    at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:722)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:549)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:360)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by enriquepiatti** [comment]
Which Magicento version are you using Fabian?

**Comment by Schrank** [comment]
Hey Enrique, it's 2.7.0

**Comment by enriquepiatti** [comment]
OK, I think that's the reason, this bug should be fixed in 2.7.3, I didn't release that version to all the users because it includes only small bugfixes and I know is a bit annoying to reinstall Magicento. 
I will release v2.8 soon with more features, but if you really need the fix for this please let me know and I will send you a 2.7.3 version.

**Comment by Schrank** [comment]
No need, just saw the exception in the log and reported :-)

Thanks
