### ISSUE TITLE
Error during dispatching of java.awt.event.InvocationEvent

### ISSUE THREAD

**Issue by kilmaster** [enriquepiatti/Magicento#14]
I have this error when i use the button : "remove this installer from core resource table" 

phpstorm V5
settings : Use http
Windows 7 ( apache on vmware server linux )

Error during dispatching of java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.intellij.openapi.util.EdtRunnable$1@8e0ef5,notifier=null,catchExceptions=false,when=1350417014164] on sun.awt.windows.WToolkit@64883c
java.lang.NullPointerException
    at com.magicento.actions.RemoveFromCoreResourceAction.executeAction(RemoveFromCoreResourceAction.java:41)
    at com.magicento.actions.MagicentoPhpActionAbstract.actionPerformed(MagicentoPhpActionAbstract.java:40)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:638)
    at com.intellij.ui.popup.AbstractPopup$18.run(AbstractPopup.java:1219)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:616)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:597)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:567)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:55)
    at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:102)
    at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:646)
    at java.awt.EventQueue.access$000(EventQueue.java:84)
    at java.awt.EventQueue$1.run(EventQueue.java:607)
    at java.awt.EventQueue$1.run(EventQueue.java:605)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:616)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:718)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:543)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:421)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:379)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by enriquepiatti** [comment]
Hi kilmaster, why are you using HTTP? are you working on a Virtual Machine? can you test the action "Evalueate in Magento" (Alt+M)? put something like "1+2", you should see 3 as the response.
Is this happening on all your magento projects?

**Comment by kilmaster** [comment]
Hej, yes i'm using a virtual machine.
No :Evaluate in magento doesn't work. A popup appear, but with nothing inside. I will try to go back on php storm 4 because "evaluate in magento" was working.

( I haven't try on other project , but it works on a other computer with phpstorm 4 )

**Comment by enriquepiatti** [comment]
OK, I think I found the error, but it's really weird if it's working on PHPStorm 4 (the problem seems to be the VM not the IDE).
Do you want to add me to skype? (enriquepiatti), I think I can help you to solve the problem and then release the fix.

**Comment by nemphys** [comment]
Any news on this one? I am having the same problem in PHPStorm 5.0.4

**Comment by enriquepiatti** [comment]
It should work with the last magicento version, what version are you using nemphys? also can you show me your Magicento Settings?

**Comment by nemphys** [comment]
I'm using 0.9.8; as for the settings, not much there got here you go:
https://dl.dropbox.com/u/24277766/Magicento%20config.jpg

**Comment by enriquepiatti** [comment]
please check this nemphys:
visit with your browser:
http://[your local magento domain from magicento settings]/.idea/magicento/eval.php
and see what happens
also, check the file eval.php inside /Users/Nemphys/magento/.idea/magicento/eval.php

let me know

**Comment by nemphys** [comment]
ok, just fixed it (had a wrong store value set; realized that when I edited eval.php to see it's contents). Now works with the php interpreter option, too.
Sorry for the trouble, nice work!
