### ISSUE TITLE
Magicento 

### ISSUE THREAD

**Issue by avoelkl** [enriquepiatti/Magicento#154]
Hi,

Fyi, i just tried Magicento with PhpStorm EAP for 9.0 EAP 141.89, March 9 on Windows and got an error:
https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Early+Access+Program

```
Plugin 'Magicento' failed to initialize and will be disabled.  Please restart PhpStorm.

java.lang.NoClassDefFoundError: com/intellij/ide/reporter/ConnectionException
    at com.magicento.MagicentoApplicationComponent.initComponent(MagicentoApplicationComponent.java:88)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:568)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:610)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:125)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:359)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:116)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:504)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:486)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:64)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.ClassNotFoundException: com.intellij.ide.reporter.ConnectionException PluginClassLoader[Magicento, 2.7.3]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 29 more
```

**Comment by enriquepiatti** [comment]
Hi @avoelkl which Magicento version are you using?

**Comment by avoelkl** [comment]
Hi @enriquepiatti, I'm using Version 2.9.0.

**Comment by enriquepiatti** [comment]
that's weird there isn't any reference about ConnectionException in 2.9.0, it was fixed in that version, even more, there isn't any executable code in line MagicentoApplicationComponent.java:88, those lines were changed in 2.9.0 too.
Maybe there was an issue with the compilation for your plugin, please send me an email I will generate it again.

**Comment by avoelkl** [comment]
Hi @enriquepiatti, seems it was my fault.
I re-installed PHPStorm EAP for 9.0 now (same .exe) as well as Magicento. It works now. Think I might have used an old .jar of Magicento before that was on my disk. Just enabled Magicento again and it works with the EAP.
Thanks for looking into that!
