### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by infabo** [enriquepiatti/Magicento#156]
On PHPStorm PS-141.332

```
null
java.lang.NullPointerException
    at com.magicento.actions.CopyTemplateAction.isApplicable(CopyTemplateAction.java:33)
    at com.magicento.MagicentoAction._getMagentoContextActions(MagicentoAction.java:124)
    at com.magicento.MagicentoAction.executeAction(MagicentoAction.java:29)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:370)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:586)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:637)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:476)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by infabo** [comment]
It occurs when I create a new project, add magento source as an external library and then want to enable Magicento.

**Comment by infabo** [comment]
OK, seems like this error only occurs, when I'm inside a non php-file. ALT+M inside e.g. the modman file throws this exception. Should be handled though.

**Comment by enriquepiatti** [comment]
I think this could happen when using ALT+M on any file without extension. The fix will be included in the next release.
Thanks @infabo !
