### ISSUE TITLE
Issue creating Model Triad

### ISSUE THREAD

**Issue by SkepticalHippo** [enriquepiatti/Magicento#161]
Whenever creating a model triad in a module created via Magicento or a manually created one it results in this error:

IncorrectOperationException: Element cannot be added

There is also a stack trace provided by PhpStorm:

```
Element cannot be added
com.intellij.util.IncorrectOperationException: Element cannot be added
    at com.intellij.psi.impl.source.tree.CompositePsiElement.a(CompositePsiElement.java:316)
    at com.intellij.psi.impl.source.tree.CompositePsiElement.add(CompositePsiElement.java:149)
    at com.magicento.helpers.XmlHelper$2.run(XmlHelper.java:840)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:977)
    at com.magicento.helpers.XmlHelper.setValue(XmlHelper.java:836)
    at com.magicento.helpers.XmlHelper.createTagUsingMagicentoSuggestions(XmlHelper.java:795)
    at com.magicento.actions.CreateModelTriadAction.executeAction(CreateModelTriadAction.java:63)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:370)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:739)
    at com.intellij.ui.popup.AbstractPopup$18.run(AbstractPopup.java:1343)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:651)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:632)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:602)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
    at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:108)
    at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

PhpStorm version: 8.0.3  
Magicento version: 2.9.1

**Comment by enriquepiatti** [comment]
Hi @SkepticalHippo is this problem still happening? (last Magicento version is 2.9.4, please contact me  by email if you have an old version)

**Comment by Koc** [comment]
@enriquepiatti does 2.9.4 version is released? I have 2.9.0, how it possible to update?

**Comment by enriquepiatti** [comment]
Hi @Koc please send me an email and I will check your user and version

**Comment by Koc** [comment]
@enriquepiatti I've send you email to contacto@enriquepiatti.com but there is no any answer :(.

**Comment by enriquepiatti** [comment]
Hi @Koc I didn't received it, maybe was filtered as SPAM? try again with a copy to enrique.piatti@gmail.com just in case.
And you can always contact me by skype too: enriquepiatti
