### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by procinger** [enriquepiatti/Magicento#163]
Hi,

i can't open the Magicento settings ( File -> Settings -> Magicento). The plugin is crashing with a NullPointerException.

The context menu (Alt + m / Option + M) is working fine.

I'm using PhpStorm 8.0.3 Build PS-139.1348, Magicento 2.9.1 on Mac OSX 10.9.5 and 10.10.3

[  31053]  ERROR - plication.impl.ApplicationImpl - null 
java.lang.NullPointerException
    at com.magicento.MagicentoSettings.hasMagentoPathInCurrentProject(MagicentoSettings.java:507)
    at com.magicento.MagicentoSettings.getInstance(MagicentoSettings.java:105)
    at com.magicento.ui.forms.MagicentoSettingsForm.createComponent(MagicentoSettingsForm.java:413)
    at com.intellij.openapi.options.newEditor.OptionsEditor$Simple.<init>(OptionsEditor.java:1052)
    at com.intellij.openapi.options.newEditor.OptionsEditor.c(OptionsEditor.java:507)
    at com.intellij.openapi.options.newEditor.OptionsEditor.access$1900(OptionsEditor.java:67)
    at com.intellij.openapi.options.newEditor.OptionsEditor$9$1$1.run(OptionsEditor.java:476)
    at com.intellij.openapi.application.impl.ApplicationImpl.runEdtSafeAction(ApplicationImpl.java:1093)
    at com.intellij.openapi.options.newEditor.OptionsEditor$9$1.run(OptionsEditor.java:469)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:908)
    at com.intellij.openapi.options.newEditor.OptionsEditor$9.run(OptionsEditor.java:466)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
[  31055]  ERROR - plication.impl.ApplicationImpl - PhpStorm 8.0.3  Build #PS-139.1348 
[  31055]  ERROR - plication.impl.ApplicationImpl - JDK: 1.6.0_65 
[  31055]  ERROR - plication.impl.ApplicationImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
[  31055]  ERROR - plication.impl.ApplicationImpl - Vendor: Apple Inc. 
[  31055]  ERROR - plication.impl.ApplicationImpl - OS: Mac OS X 
[  31055]  ERROR - plication.impl.ApplicationImpl - Last Action: TemplateProjectProperties

**Comment by haocongnghe** [comment]
My Magicento is same as. It has shown java.lang.NullPointerException. I'm using PHP Storm 8.0.3 and Mac OS 10.10.3

**Comment by enriquepiatti** [comment]
I need more information about this, if this happens with all the projects if it's blocking the other functions etc, please contact me by email

**Comment by enriquepiatti** [comment]
There is a fix for this (not officialy released yet), please the people having this problem contact me by email and I will send you a special version

**Comment by haocongnghe** [comment]
Hi,
Please send me fix versions. I have a problem with plugin on Mac OS
10.10.3, PHP Storm 8.0.3.

Thanks

On Wed, May 20, 2015 at 9:57 PM, Enrique Piatti notifications@github.com
wrote:

> There is a fix for this (not officialy released yet), please the people
> having this problem contact me by email and I will send you a special
> version
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/enriquepiatti/Magicento/issues/163#issuecomment-103918209
> .

## 

_Trương Văn Hào_

**Comment by enriquepiatti** [comment]
@haobkit sned me an email, I can't send you the fixed version here.
But anyone, just in case, this could be a problem related with the menu in PhpStorm, it doesn't have the option "Settings" only "Default Settings", you should not use that, try to open the settings menu in other way:

https://www.jetbrains.com/phpstorm/help/accessing-settings.html?search=settings

**Comment by haocongnghe** [comment]
Thank you, I tried to open the settings by your way and enable Magicento
successfully.

On Mon, Jun 1, 2015 at 9:26 PM, Enrique Piatti notifications@github.com
wrote:

> @haobkit https://github.com/haobkit sned me an email, I can't send you
> the fixed version here.
> But anyone, just in case, this could be a problem related with the menu in
> PhpStorm, it doesn't have the option "Settings" only "Default Settings",
> you should not use that, try to open the settings menu in other way:
> 
> https://www.jetbrains.com/phpstorm/help/accessing-settings.html?search=settings
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/enriquepiatti/Magicento/issues/163#issuecomment-107519867
> .

## 

_Trương Văn Hào_
