### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by Celldweller** [enriquepiatti/Magicento#165]
Unfortunately I experience massive amounts of java.util.ConcurrentModificationException

It happens appr. 20-30 times per day.

Magicento Version is 2.9.0
PHPStorm Version is 8.0.3 on Mac 10.10.3

What I also experience is, everytime I use Alt+M and Flush Cache, I get an error:
Magicento Notification: Error flushing the cache

null
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.remove(HashMap.java:811)
    at com.magicento.helpers.IdeHelper.showNotification(IdeHelper.java:198)
    at com.magicento.MagicentoSettings.getInstance(MagicentoSettings.java:118)
    at com.magicento.extensions.intention.CreateTemplateFile.isAvailable(CreateTemplateFile.java:75)
    at com.intellij.codeInsight.intention.PsiElementBaseIntentionAction.isAvailable(PsiElementBaseIntentionAction.java:64)
    at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.isAvailable(IntentionActionWrapper.java:56)
    at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.a(ShowIntentionActionsHandler.java:113)
    at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:104)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass$3.process(ShowIntentionsPass.java:287)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass$3.process(ShowIntentionsPass.java:284)
    at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:138)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:283)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.a(ShowIntentionsPass.java:210)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:186)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1146)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

**Comment by enriquepiatti** [comment]
Hi @Celldweller contact me by email, there is a version with a fix for this

**Comment by enriquepiatti** [comment]
As a side note, a possible workaround (found by @Celldweller could be to remove the .idea folder and recreate the project)

**Comment by Celldweller** [comment]
Unfortunately the error shows up furthermore.
I guess it could have something to do with different projects open at the same time.

**Comment by enriquepiatti** [comment]
what version are you using now? please contact me by email and I will send you the last version available (2.9.3)
But yes, Magicento could have some problems if you have multiple projects opened at the same time, I recommend to open just one when it's possible.
