### ISSUE TITLE
IllegalArgumentException: Argument for @NotNull parameter 'file' of com/magicento/models/layout/LayoutFile. must not be null

### ISSUE THREAD

**Issue by Celldweller** [enriquepiatti/Magicento#177]
Since I opened app/design/frontend/base/default/template/checkout/onepage/shipping.phtml I get repeating errors:

19:10:25 IllegalArgumentException: Argument for @NotNull parameter 'file' of com/magicento/models/layout/LayoutFile. must not be null (show balloon)
19:10:45 IllegalArgumentException: Argument for @NotNull parameter 'file' of com/magicento/models/layout/LayoutFile. must not be null (show balloon)
19:10:52 IllegalArgumentException: Argument for @NotNull parameter 'file' of com/magicento/models/layout/LayoutFile. must not be null (show balloon)
19:10:57 IllegalArgumentException: Argument for @NotNull parameter 'file' of com/magicento/models/layout/LayoutFile. must not be null (show balloon)
19:11:01 IllegalArgumentException: Argument for @NotNull parameter 'file' of com/magicento/models/layout/LayoutFile. must not be null (show balloon)
19:11:14 IllegalArgumentException: Argument for @NotNull parameter 'file' of com/magicento/models/layout/LayoutFile. must not be null (show balloon)
19:11:16 IllegalArgumentException: Argument for @NotNull parameter 'file' of com/magicento/models/layout/LayoutFile. must not be null (show balloon)
19:11:36 IllegalArgumentException: Argument for @NotNull parameter 'file' of com/magicento/models/layout/LayoutFile. must not be null (show balloon)
19:12:00 IllegalArgumentException: Argument for @NotNull parameter 'file' of com/magicento/models/layout/LayoutFile. must not be null (show balloon)
19:12:02 IllegalArgumentException: Argument for @NotNull parameter 'file' of com/magicento/models/layout/LayoutFile. must not be null (show balloon)
19:12:26 IllegalArgumentException: Argument for @NotNull parameter 'file' of com/magicento/models/layout/LayoutFile. must not be null (show balloon)

Other Templates don't throw this error.

Any idea how this happens?

Thanks and best regards!

**Comment by Celldweller** [comment]
While checking I noticed that the error disappears after I used "add @var $this" within the template, which successfully added the doc comment.

The version I use is 2.9.0

**Comment by enriquepiatti** [comment]
is weird anyway, if you have full stack trace please send it to me or put it here.
Thanks!

**Comment by Celldweller** [comment]
Sure :-)

I can reproduce the error easily be removing the @var $this line:

```
Argument for @NotNull parameter 'file' of com/magicento/models/layout/LayoutFile.<init> must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/magicento/models/layout/LayoutFile.<init> must not be null
    at com.magicento.models.layout.LayoutFile.<init>(LayoutFile.java)
    at com.magicento.models.layout.Template.<init>(Template.java:24)
    at com.magicento.extensions.BlockTypeProvider2.getBySignature(BlockTypeProvider2.java:75)
    at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:418)
    at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:304)
    at com.jetbrains.php.PhpIndexImpl.getClasses(PhpIndexImpl.java:449)
    at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:393)
    at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:304)
    at com.jetbrains.php.PhpIndexImpl.getClasses(PhpIndexImpl.java:449)
    at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:393)
    at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:304)
    at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:294)
    at com.jetbrains.php.lang.psi.resolve.types.PhpParameterBasedTypeProvider.getTargets(PhpParameterBasedTypeProvider.java:141)
    at com.jetbrains.php.lang.psi.resolve.types.PhpParameterBasedTypeProvider.getBySignature(PhpParameterBasedTypeProvider.java:117)
    at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:418)
    at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:304)
    at com.jetbrains.php.PhpIndexImpl.getClasses(PhpIndexImpl.java:449)
    at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:393)
    at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:304)
    at com.jetbrains.php.PhpIndexImpl.getClasses(PhpIndexImpl.java:449)
    at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:393)
    at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:304)
    at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:81)
    at com.jetbrains.php.lang.psi.resolve.types.PhpType.global(PhpType.java:431)
    at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection.analyzeCall(PhpVoidFunctionResultUsedInspection.java:47)
    at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection.access$000(PhpVoidFunctionResultUsedInspection.java:21)
    at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection$1.visitPhpMethodReference(PhpVoidFunctionResultUsedInspection.java:39)
    at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:30)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:80)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:309)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:304)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by Celldweller** [comment]
Not sure if this belongs to the problem, but I recently updated X-Code on my Mac (OSX 10.10.5). It is remarkable because you needed to accept the license agreement again. Otherwise it lead to strange behaviour and errors because without accepting the bash did not fully work.
Perhaps there were other updates e.g. for Java as well?

I never had this error before until today.

**Comment by enriquepiatti** [comment]
OK, I have added a fix to that (just to prevent the exception for now, not sure why the @var $this is doing that in that file...).
Thanks !
