### ISSUE TITLE
PhpStorm 10.0 - IncorrectOperationException: Element cannot be added when creating model

### ISSUE THREAD

**Issue by matmarchant** [enriquepiatti/Magicento#179]
Element cannot be added
com.intellij.util.IncorrectOperationException: Element cannot be added
    at com.intellij.psi.impl.source.tree.CompositePsiElement.a(CompositePsiElement.java:322)
    at com.intellij.psi.impl.source.tree.CompositePsiElement.add(CompositePsiElement.java:151)
    at com.magicento.helpers.XmlHelper$2.run(XmlHelper.java:840)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1002)
    at com.magicento.helpers.XmlHelper.setValue(XmlHelper.java:836)
    at com.magicento.helpers.XmlHelper.createTagUsingMagicentoSuggestions(XmlHelper.java:795)
    at com.magicento.actions.CreateModelTriadAction.executeAction(CreateModelTriadAction.java:63)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:370)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:856)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:842)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by enriquepiatti** [comment]
Hi @maximinimus is this error still happening? if yes I think I need more info about the context to check it better (you can send me an email is the information is private)
