### ISSUE TITLE
Argument for @NotNull parameter 'element' of com/magicento/helpers/IdeHelper.reformat must not be null

### ISSUE THREAD

**Issue by Schrank** [enriquepiatti/Magicento#182]
```
Argument for @NotNull parameter 'element' of com/magicento/helpers/IdeHelper.reformat must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'element' of com/magicento/helpers/IdeHelper.reformat must not be null
    at com.magicento.helpers.IdeHelper.reformat(IdeHelper.java)
    at com.magicento.actions.CreateModuleAction.reformatFile(CreateModuleAction.java:230)
    at com.magicento.actions.CreateModuleAction.createModuleXmlFile(CreateModuleAction.java:222)
    at com.magicento.actions.CreateModuleAction.executeAction(CreateModuleAction.java:56)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:370)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:856)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:842)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by enriquepiatti** [comment]
@Schrank seems like you were trying to create a module, do you remember if it failed? looks like the xml file in "/app/etc/modules/" was not created correctly (or at all), maybe your project has a special structure? (virtual machines, modman, etc)

**Comment by Schrank** [comment]
Everything. I have VMs and modman running. But this happend only once. And it might be, that the file wasn't created. not sure.
