### ISSUE TITLE
Worker exited due to exception: String index out of range: -1

### ISSUE THREAD

**Issue by shadowice222** [enriquepiatti/Magicento#186]
After upgrading PHPStorm to 2016.1

```
Worker exited due to exception: String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(String.java:1967)
    at com.magicento.helpers.JavaHelper.trimQuotes(JavaHelper.java:444)
    at com.magicento.helpers.MagentoParser.getFilePath(MagentoParser.java:159)
    at com.magicento.helpers.MagentoParser.isFilePath(MagentoParser.java:150)
    at com.magicento.extensions.MagicentoGotoDeclarationHandler.getGotoDeclarationTargets(MagicentoGotoDeclarationHandler.java:115)
    at com.magicento.extensions.MagicentoGotoDeclarationHandler.getGotoDeclarationTargets(MagicentoGotoDeclarationHandler.java:53)
    at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:245)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:531)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:510)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2600(CtrlMouseHandler.java:106)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:846)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2500(CtrlMouseHandler.java:786)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:831)
    at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:70)
    at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:67)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
    at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:67)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils$7.compute(ProgressIndicatorUtils.java:227)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils$7.compute(ProgressIndicatorUtils.java:223)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:162)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:159)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:223)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:45)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils$6$2.run(ProgressIndicatorUtils.java:188)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by pod6wasjerks** [comment]
I'm having this issue as well, it happens quite frequently.

> 2:00:08 PM StringIndexOutOfBoundsException: Worker exited due to exception: String index out of range: -1
> 2:00:15 PM StringIndexOutOfBoundsException: Worker exited due to exception: String index out of range: -1
> 2:01:31 PM StringIndexOutOfBoundsException: Worker exited due to exception: String index out of range: -1
> 2:03:58 PM StringIndexOutOfBoundsException: Worker exited due to exception: String index out of range: -1
> 2:04:03 PM StringIndexOutOfBoundsException: Worker exited due to exception: String index out of range: -1

**Comment by enriquepiatti** [comment]
Hi @shadowice222  and @pod6wasjerks, what version of Magicento are you using, this looks like an error fixed in 2.9.3

**Comment by pod6wasjerks** [comment]
2.9.2. Apologies, @enriquepiatti , I was unaware 2.9.3 had released. I am still within my license but the Magicento menu is not displaying the "Update Magicento" dialog. Can I email you my order number to receive a link?

**Comment by enriquepiatti** [comment]
sure please send me an email @pod6wasjerks
