### ISSUE TITLE
Can't create controller with Magicento 2

### ISSUE THREAD

**Issue by matiasserrano** [enriquepiatti/Magicento#190]
When I tried to create a new controller with Magicento 2 I get a Null Pointer Exception.

null
java.lang.NullPointerException
    at com.magicento.ui.dialog.CreateControllerDialog.updateBasePath(CreateControllerDialog.java:83)
    at com.magicento.ui.dialog.CreateControllerDialog.createCenterPanel(CreateControllerDialog.java:69)
    at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1280)
    at com.magicento.ui.dialog.ChooseModuleDialog.init(ChooseModuleDialog.java:124)
    at com.magicento.ui.dialog.CreateControllerDialog.<init>(CreateControllerDialog.java:53)
    at com.magicento.actions.CreateControllerAction.executeAction(CreateControllerAction.java:26)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:370)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:861)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:847)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by enriquepiatti** [comment]
Hi @matiasserrano are you coding with Magento or Magento2? because you mentioned Magicento 2 but the stack trace indicates you are using Magicento1

**Comment by matiasserrano** [comment]
Basically, I have both plugins installed. The project is Magento 2. Perhaps is an issue related to have both Magicento 1 and Magicento 2 installed at the same time. (btw, is the only thing failing, the others works great)

**Comment by enriquepiatti** [comment]
@matiasserrano have you followed these instructions?
http://magicento.com/#magicento2_installation
ALT+M should open Magicento2 options if your project is Magento2 (also make sure Magicento1 is disabled for your Magento2 project)

**Comment by matiasserrano** [comment]
Thx, I followed those instructions and is working fine now. Thx!!!!
