### ISSUE TITLE
Can't create model triad - java.lang.AssertionError

### ISSUE THREAD

**Issue by spyro1st** [enriquepiatti/Magicento#193]
Hi,

when i try to create a model triad i receive this exception:

`null
java.lang.AssertionError
    at com.magicento.helpers.XmlHelper.createTagUsingMagicentoSuggestions(XmlHelper.java:788)
    at com.magicento.actions.CreateModelTriadAction.executeAction(CreateModelTriadAction.java:63)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:405)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:861)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:847)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

What could be the reason for this?

Magicento version is 2.9.4 and PhpStorm version is 2016.1 on OS X 10.11.6

PhpStorm 2016.1
Build #PS-145.258, built on March 16, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by spyro1st** [comment]
Any answer on this? Else the plugin is not really useful for me.

**Comment by enriquepiatti** [comment]
Hi @km-digitalpatrioten please send me an email because I will need info about your project and maybe is not good to post it here in public.
But you can try also creating a new project, based on a new and clean Magento install (unzip some original Magento code, don't use n98 or modman or any custom modules, just Magento), create a new module with Magicento and then try using the model triad option on that module. Let me know if it works in that case.
Also send me by email (or paste it here if is not a problem for you) a screenshot showing dialog box and the data you are using to create the model triad

**Comment by riconeitzel** [comment]
@enriquepiatti I'm sure you can close this one
