### ISSUE TITLE
Magento2 Create Module under different root.

### ISSUE THREAD

**Issue by idmistir** [enriquepiatti/Magicento#195]
Under a different tree structure (my magento2 installation is in project_root/subfolder/mage) Create Module is not working for me. Create Module tries to create the module on project_root and throws an IndexOutofBounds exception.

Also, question: is magicento still in active development?

`Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at com.magicento2.actions.CreateModuleAction.enableModule(CreateModuleAction.java:85)
    at com.magicento2.actions.CreateModuleAction.executeAction(CreateModuleAction.java:76)
    at com.magicento2.actions.Magicento2ActionAbstract.actionPerformed(Magicento2ActionAbstract.java:407)
    at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
    at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
    at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:875)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.a(PopupFactoryImpl.java:863)
    at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
    at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1390)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:863)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by enriquepiatti** [comment]
Hi @idmistir, are you sure Magicento settings are correct? you need to configure the paths for Magento there
But I highly recommend to create a new project based on your Magento root folder, is there any reason why you are using a parent folder for the project? it will make Magicento (and PhpStorm in general) slower, because it needs to scan more files

**Comment by enriquepiatti** [comment]
With last version (1.2.0) your PhpStorm project root does not need to be the same as your Magento2 root folder. You can configura the path to Magento2 from Magicento2 settings.
Please reopen if you find any issue with that option.

**Comment by idmistir** [comment]
@enriquepiatti This functionality is very useful with custom code structures (e.g modman). Being able to do module development outside the root folder is great to have. I'll test this with M2. With M1, since autocompletion doesn't work outside the project root for me, if I deploy with modman and the symlink gets created, then I get the functionality back.

Thanks!
