### ISSUE TITLE
Magento 2 no longer uses Mage.php

### ISSUE THREAD

**Issue by rdicristino** [enriquepiatti/Magicento#198]
I went to set Mage.php and found that magento 2 no longer uses that. So how do I use the functionality of your plugin without that as it is saying that it's required. Plus I keep getting this error "NullPointerException: null null
java.lang.NullPointerException
    at com.magicento.models.xml.layout.MagentoLayoutXml.setArea(MagentoLayoutXml.java:252)
    at com.magicento.MagicentoProjectComponent.getCachedLayoutXmlDocument(MagicentoProjectComponent.java:211)
    at com.magicento.models.layout.Template.getBlockElements(Template.java:51)
    at com.magicento.models.layout.Template.getBlocksClasses(Template.java:114)
    at com.magicento.extensions.BlockTypeProvider2.getBySignature(BlockTypeProvider2.java:77)
    at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:476)
    at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:320)
    at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:81)
    at com.jetbrains.php.lang.psi.resolve.types.PhpType.globalLocationAware(PhpType.java:410)
    at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.resolveGlobal(MemberReferenceImpl.java:145)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:144)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:141)
    at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
    at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.multiResolve(PhpReferenceImpl.java:136)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.resolve(PhpReferenceImpl.java:122)
    at com.jetbrains.php.lang.inspections.PhpMethodParametersCountMismatchInspection$1.inspect(PhpMethodParametersCountMismatchInspection.java:40)
    at com.jetbrains.php.lang.inspections.PhpMethodParametersCountMismatchInspection$1.visitPhpMethodReference(PhpMethodParametersCountMismatchInspection.java:94)
    at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:29)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
    at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:286)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:254)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:123)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1026)
    at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:96)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)" in the install. I just bought your plugin and haven't been able to use it at all.

Could you shed some light on this for me please?

**Comment by enriquepiatti** [comment]
Hi @rdicristino make sure you are not using Magicento1 with Magento2, there is a different plugin for Magento2, please read
http://magicento.com/#magicento2_installation
http://magicento.com/#changelog_magicento2

**Comment by rdicristino** [comment]
Hey @enriquepiatti If it says magicento on the install rather than magicento2 then that is the wrong one? My page refreshed before I bought so I thought that it was still the same product as nothing looked different. If this is the case can I swap the item out? I do not use magento 1 so it would be useless for me to have.

**Comment by rdicristino** [comment]
Btw @enriquepiatti, I forgot to mention, I have the confirmation number for paypal and the order number I received in my email if that will help.

**Comment by enriquepiatti** [comment]
@rdicristino send me an email with your order number if you lost your private link
