### ISSUE TITLE
RuntimeException: Invalid version number: PS-162.1121.38

### ISSUE THREAD

**Issue by ilya-kush** [enriquepiatti/Magicento#200]
I am getting errors when I try to add private code in Magicento settings.

"RuntimeException: Invalid version number: PS-162.1121.38; plugin name: null: Invalid version number: PS-162.1121.38; plugin name: null"

java.lang.RuntimeException: Invalid version number: PS-162.1121.38; plugin name: null
    at com.intellij.openapi.util.BuildNumber.parseBuildNumber(BuildNumber.java:136)
    at com.intellij.openapi.util.BuildNumber.fromString(BuildNumber.java:112)
    at com.intellij.openapi.util.BuildNumber.fromString(BuildNumber.java:76)
    at com.magicento.helpers.IdeHelper.isPhpStorm2016_2_orHigher(IdeHelper.java:715)
    at com.magicento.ui.forms.MagicentoSettingsForm.createComponent(MagicentoSettingsForm.java:533)
    at com.intellij.openapi.options.newEditor.OptionsEditor$Simple.<init>(OptionsEditor.java:1303)
    at com.intellij.openapi.options.newEditor.OptionsEditor.b(OptionsEditor.java:461)
    at com.intellij.openapi.options.newEditor.OptionsEditor.access$2500(OptionsEditor.java:68)
    at com.intellij.openapi.options.newEditor.OptionsEditor$9$1$1.run(OptionsEditor.java:430)
    at com.intellij.openapi.application.impl.ApplicationImpl.runEdtSafeAction(ApplicationImpl.java:1098)
    at com.intellij.openapi.options.newEditor.OptionsEditor$9$1.run(OptionsEditor.java:423)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:908)
    at com.intellij.openapi.options.newEditor.OptionsEditor$9.run(OptionsEditor.java:420)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:420)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:150)

**Comment by enriquepiatti** [comment]
Hi @ilya-kush what version of PhpStorm are you using? and what OS?

**Comment by ilya-kush** [comment]
@enriquepiatti  PHPStorm 7.1.3  Windows 8.1

**Comment by enriquepiatti** [comment]
that version of PhpStorm is really old @ilya-kush I guess you will miss a lot of features of Magicento if you don't update it.
Anyway, I have added a bugfix for that, please try downloading Magicento and install it again, and let me know if it's fixed

**Comment by ilya-kush** [comment]
@enriquepiatti thank You. now it works. I will update PhpStorm also.
