### ISSUE TITLE
[Magento2] Argument for @NotNull parameter 'phpClass' of com/magicento2

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#211]
```
Argument for @NotNull parameter 'phpClass' of com/magicento2/models/phpclass/InterceptedClass.<init> must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'phpClass' of com/magicento2/models/phpclass/InterceptedClass.<init> must not be null
	at com.magicento2.models.phpclass.InterceptedClass.<init>(InterceptedClass.java)
	at com.magicento2.extensions.linemarker.PluginLineMarkerProvider._collectSlowLineMarkers(PluginLineMarkerProvider.java:52)
	at com.magicento2.extensions.linemarker.Magicento2LineMarkerProviderAbstract.collectSlowLineMarkers(Magicento2LineMarkerProviderAbstract.java:39)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:78)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:65)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:434)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$$Lambda$837/282414341.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1026)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:427)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$$Lambda$829/1374177086.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by enriquepiatti** [comment]
Solved. Will be available with the next release (in a few days). Thanks !
