### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by Kompas** [enriquepiatti/Magicento#22]
Not sure what happened. I got this error. Didn't mention it untill JetBrains Phpstorm informed me about it.

null
java.lang.NullPointerException
    at com.magicento.models.xml.MagentoXmlFactory.getInstance(MagentoXmlFactory.java:73)
    at com.magicento.helpers.MagentoParser.isHandleNode(MagentoParser.java:603)
    at com.magicento.extensions.MagicentoGotoDeclarationHandler.getGotoDeclarationTargets(MagicentoGotoDeclarationHandler.java:240)
    at com.magicento.extensions.MagicentoGotoDeclarationHandler.getGotoDeclarationTargets(MagicentoGotoDeclarationHandler.java:48)
    at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:207)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:528)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$1900(CtrlMouseHandler.java:95)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:759)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$1800(CtrlMouseHandler.java:708)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1$1.run(CtrlMouseHandler.java:749)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:918)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils$3.run(ProgressIndicatorUtils.java:60)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:181)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:221)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:172)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:55)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.run(CtrlMouseHandler.java:747)
    at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:457)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:148)

**Comment by fplantinet** [comment]
i have this error to !

null
java.lang.NullPointerException
    at com.magicento.models.xml.MagentoXmlFactory.getInstance(MagentoXmlFactory.java:73)
    at com.magicento.helpers.MagentoParser.isHandleNode(MagentoParser.java:603)
    at com.magicento.extensions.MagicentoGotoDeclarationHandler.getGotoDeclarationTargets(MagicentoGotoDeclarationHandler.java:240)
    at com.magicento.extensions.MagicentoGotoDeclarationHandler.getGotoDeclarationTargets(MagicentoGotoDeclarationHandler.java:48)
    at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:207)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:528)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$1900(CtrlMouseHandler.java:95)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:759)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$1800(CtrlMouseHandler.java:708)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1$1.run(CtrlMouseHandler.java:749)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:918)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils$3.run(ProgressIndicatorUtils.java:60)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:181)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:221)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:172)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:55)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.run(CtrlMouseHandler.java:747)
    at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:457)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:148)

**Comment by enriquepiatti** [comment]
Fixed in v1.2.0
