### ISSUE TITLE
NullPointerException: getDocumentFromXmlString

### ISSUE THREAD

**Issue by ipascual** [enriquepiatti/Magicento#225]
- Magicento: 3.0.2
- PHPStorm: 10.0.4
- Magento EE ver. 1.14.0.1
- Mac OS Sierra
- Java 1.8.0_102

ERROR: NullPointerException: null
```null
java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:50)
	at com.magicento.helpers.XmlHelper.getDocumentFromXmlString(XmlHelper.java:185)
	at com.magicento.models.php.RemotePhpScriptsManager.parseXml(RemotePhpScriptsManager.java:62)
	at com.magicento.ui.toolwindow.MagicentoScriptsToolWindowFactory$13.doSomethingWithResult(MagicentoScriptsToolWindowFactory.java:590)
	at com.magicento.helpers.JavaHelper$4$1$2.run(JavaHelper.java:366)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2361)
	at com.magicento.helpers.JavaHelper$4$1.finished(JavaHelper.java:362)
	at com.intellij.util.concurrency.SwingWorker$1.run(SwingWorker.java:148)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ipascual** [comment]
Your server magicento.com is down (138.219.41.112). Probably that's why.

**Comment by enriquepiatti** [comment]
Yes there was a problem with the webserver, is fixed now, but reopen if you are still seeing this bug
Thanks !
