### ISSUE TITLE
Commands missing in Execute Magento Commands for one project (Magicento 2)

### ISSUE THREAD

**Issue by AreDubya** [enriquepiatti/Magicento#228]
Hi Enrique, 

I'm having an odd issue with one project where the menu in Execute Magento Commands is missing more than half of the available commands. The configuration is the same as the other projects, the projects are running on the same Vagrant box, using the same Magento version (2.1.2), same deployment strategy, same Magicento settings aside from the last folder name, same permissons on the server, and the same CLI Interpreter originally. 

The commands will execute if I type them manually, and if I open the Execute Magento2 Command window and hit "OK" without picking a command I see in the Event Log the normal output of entering "php bin/magento" on the command line ~70 commands and their descriptions. In Magicento only 32 are present. 

Also, occasionally in the Command window the name of the interpreter will be in place of "php" in the output under the command text field. 

Not sure if this has anything to do with it, but this error popped up earlier : 

`Argument for @NotNull parameter 'strings' of com/magicento2/helpers/JavaHelper.implode must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'strings' of com/magicento2/helpers/JavaHelper.implode must not be null
	at com.magicento2.helpers.JavaHelper.implode(JavaHelper.java)
	at com.magicento2.actions.CleanMagento2CacheAction$1.doSomethingWithResult(CleanMagento2CacheAction.java:36)
	at com.magicento2.helpers.PHP.executeVisitor(PHP.java:171)
	at com.magicento2.helpers.PHP.executeWithHttp(PHP.java:333)
	at com.magicento2.helpers.PHP.execute(PHP.java:70)
	at com.magicento2.helpers.PHP.executePhpWithMagento(PHP.java:54)
	at com.magicento2.actions.CleanMagento2CacheAction.executeAction(CleanMagento2CacheAction.java:23)
	at com.magicento2.actions.Magicento2PhpActionAbstract.actionPerformed(Magicento2PhpActionAbstract.java:20)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:879)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.a(PopupFactoryImpl.java:867)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1392)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

How can I get Magicento2 to pull in the complete list of commands?

Thanks

**Comment by enriquepiatti** [comment]
Hi @AreDubya have you solved this? I think must be an issue with your indexes, try clearing Magicento 2 indexes, or use File > Invalidate Cache Restart option. The commands are read directly from the code.
If the problem persist then can you detect some pattern on the commands Magicento2 is not detecting? maybe they are in some specific folders, or are custom commands created by you etc

Regarding to the other error, I think that's because your PHP config in Magicento2 settings is not correct, are the PHP features working correctly? please make sure to read the docs there, depending on your project config could be a bit tricky to set everything properly.
