### ISSUE TITLE
[Magento 1] com.jetbrains.php.lang.psi.elements.ExtendsList.getReferenceElement() error

### ISSUE THREAD

**Issue by alvinnguyen** [enriquepiatti/Magicento#229]
@enriquepiatti 

This bug from EAP has moved into Stable release (#202 #205) on Mac OS

PhpStorm 2016.3.2
Build #PS-163.10504.2, built on December 21, 2016
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Having this issue on Magicento 2.9.0 when trying to create Grid and Form

```
com.jetbrains.php.lang.psi.elements.ExtendsList.getReferenceElement()Lcom/jetbrains/php/lang/psi/elements/ClassReference;
java.lang.NoSuchMethodError: com.jetbrains.php.lang.psi.elements.ExtendsList.getReferenceElement()Lcom/jetbrains/php/lang/psi/elements/ClassReference;
	at com.magicento.helpers.PsiPhpHelper.getExtendsClassName(PsiPhpHelper.java:586)
	at com.magicento.helpers.PsiPhpHelper.getParents(PsiPhpHelper.java:558)
	at com.magicento.ui.dialog.CreateGridAndFormDialog.getControllers(CreateGridAndFormDialog.java:290)
	at com.magicento.ui.dialog.CreateGridAndFormDialog.updateControllers(CreateGridAndFormDialog.java:227)
	at com.magicento.ui.dialog.CreateGridAndFormDialog$2.actionPerformed(CreateGridAndFormDialog.java:115)
	at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1258)
	at javax.swing.JComboBox.contentsChanged(JComboBox.java:1332)
	at javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:118)
	at javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:93)
	at javax.swing.DefaultComboBoxModel.addElement(DefaultComboBoxModel.java:131)
	at javax.swing.JComboBox.addItem(JComboBox.java:716)
	at com.magicento.ui.dialog.ChooseModuleDialog.updateModulesComboItems(ChooseModuleDialog.java:167)
	at com.magicento.ui.dialog.ChooseModuleDialog$1.actionPerformed(ChooseModuleDialog.java:83)
	at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1258)
	at javax.swing.JComboBox.setSelectedItem(JComboBox.java:586)
	at com.magicento.ui.dialog.CreateGridAndFormDialog.setCodePool(CreateGridAndFormDialog.java:88)
	at com.magicento.actions.CreateGridAndFormAction.executeAction(CreateGridAndFormAction.java:48)
	at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:370)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:879)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.a(PopupFactoryImpl.java:867)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1394)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by enriquepiatti** [comment]
Hi @alvinnguyen please update to the last version, 2.9.0 is old, last version is 3.1.0

**Comment by vitalygrigorishin** [comment]
hi @enriquepiatti, I am trying to update magicento from 2.9.0 to 3.1.0, but it doesn't work for me. I don't have link to update.
