### ISSUE TITLE
IDE Error after clicking any new item in 'option+m' menu

### ISSUE THREAD

**Issue by pacbroens** [enriquepiatti/Magicento#233]
This morning I updated to the latest magicento2 version. And applied the latest PHPStorm patch. Enabled the plugin, opened 1 project (magento2 obviously) and tried the new features, but every item I click in the popup menu results in an error:

```
null
java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at com.magicento2.ui.components.ModulesComboBox.fillModules(ModulesComboBox.java:35)
	at com.magicento2.ui.components.ModulesComboBox.init(ModulesComboBox.java:26)
	at com.magicento2.ui.dialog.NewControllerDialog.createCenterPanel(NewControllerDialog.java:47)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1307)
	at com.magicento2.ui.dialog.NewControllerDialog.<init>(NewControllerDialog.java:39)
	at com.magicento2.actions.CreateControllerAction.executeAction(CreateControllerAction.java:32)
	at com.magicento2.actions.Magicento2ActionAbstract.actionPerformed(Magicento2ActionAbstract.java:418)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:879)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.a(PopupFactoryImpl.java:867)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1394)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

After that the plugin popup does still work, except thus for the new items in there.

I hope you can help me with this, thanks in advance!

**Comment by enriquepiatti** [comment]
Please see #234
