### ISSUE TITLE
[Magento 2] An exception occured on generating crud for model

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#270]
I've opened model class, `alt+m`, create crud model 

```
null
java.lang.NullPointerException
	at com.magicento2.ui.dialog.NewCRUDDialog.updateLabels(NewCRUDDialog.java:117)
	at com.magicento2.ui.dialog.NewCRUDDialog.createCenterPanel(NewCRUDDialog.java:45)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1308)
	at com.magicento2.ui.dialog.NewCRUDDialog.<init>(NewCRUDDialog.java:34)
	at com.magicento2.actions.CreateCRUDAction.executeAction(CreateCRUDAction.java:23)
	at com.magicento2.actions.Magicento2ActionAbstract.actionPerformed(Magicento2ActionAbstract.java:424)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:968)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:958)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.a(PopupFactoryImpl.java:952)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1428)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

```
PhpStorm 2017.2.4
Build #PS-172.4155.41, built on September 15, 2017

JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```
Magicento latest stable build (1.6.0)

**Comment by enriquepiatti** [comment]
That's strange, is like if Magicento was not able to find any module.
Can you try with another dialogs like Create Admin Menu, Create Controller, Create Observer, Create Plugin etc? any dialog that allows you to select the Module, are they working or throwing the same error?

**Comment by Koc** [comment]
I've rebuild magicento indecies and error is gone. Will reopen if occurs
