### ISSUE TITLE
[Magento2] Allow jump to original/overriden layout/template

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#278]
follow up of #216

![default](https://user-images.githubusercontent.com/191082/34104114-e3a45602-e3f7-11e7-95fd-736ae0cb3ab4.png)

I'm afraid that problem comes from external libraries

![default](https://user-images.githubusercontent.com/191082/34104159-09a1143a-e3f8-11e7-9ac6-9b8de66b619e.png)

**Comment by enriquepiatti** [comment]
Hi @Koc using ALT+M is not showing the option "Go to override view file" either?
Is failing only on this file?
Have you tried refreshing Magicento indexes or full PhpStorm index?

**Comment by Koc** [comment]
Oh, indeed, thank you. I'm always forgotting about alt+m. Just expected this functionality as linekarker. Is it possible create linemarker in future?

**Comment by enriquepiatti** [comment]
Linemarker should work too, maybe there is a problem with indexes, or maybe
the external library if you can't see any linemarker

El 27 dic. 2017 10:51, "Konstantin Myakshin" <notifications@github.com>
escribió:

Oh, indeed, thank you. I'm always forgotting about alt+m. Just expected
this functionality as linekarker. Is it possible create linemarker in
future?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/enriquepiatti/Magicento/issues/278#issuecomment-354141826>,
or mute the thread

**Comment by Koc** [comment]
No original template file. Only blocks and layouts.

![default](https://user-images.githubusercontent.com/191082/34394664-6005d49c-eb63-11e7-8892-c25f46e5aa83.png)

**Comment by Koc** [comment]
And this not work in PS 2017.3.3

```
PhpStorm 2017.3.3
Build #PS-173.4301.34, built on January 18, 2018
Licensed to PhpStorm Evaluator
Expiration date: January 21, 2018
JRE: 1.8.0_152-release-1024-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

```
0
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.magicento2.actions.Magicento2ActionAbstract.navigateToElements(Magicento2ActionAbstract.java:408)
	at com.magicento2.actions.GotoOriginalViewFileAction.executeAction(GotoOriginalViewFileAction.java:143)
	at com.magicento2.actions.Magicento2ActionAbstract.actionPerformed(Magicento2ActionAbstract.java:424)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:966)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:956)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.a(PopupFactoryImpl.java:950)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1431)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
