### ISSUE TITLE
[Magento2] - Error starting magicento2 newest PHPStorm 

### ISSUE THREAD

**Issue by rofokken** [enriquepiatti/Magicento#280]
Preconditions:

Newest PHPStorm version: 2017.3.3 Build 173.4301.43
When starting Magicento pressing alt+m an ide error occurs.

When looking at the error details i see:

Argument 2 for @NotNull parameter of com/magicento2/extensions/intention/Magicento2IntentionAbstract.isAvailable must not be null
java.lang.IllegalArgumentException: Argument 2 for @NotNull parameter of com/magicento2/extensions/intention/Magicento2IntentionAbstract.isAvailable must not be null
	at com.magicento2.extensions.intention.Magicento2IntentionAbstract.isAvailable(Magicento2IntentionAbstract.java)
	at com.magicento2.actions.IntentionAbstractAction._isApplicable(IntentionAbstractAction.java:32)
	at com.magicento2.actions.Magicento2ActionAbstract.isApplicable(Magicento2ActionAbstract.java:76)
	at com.magicento2.Magicento2Action._getMagentoContextActions(Magicento2Action.java:135)
	at com.magicento2.Magicento2Action.executeAction(Magicento2Action.java:37)
	at com.magicento2.actions.Magicento2ActionAbstract.actionPerformed(Magicento2ActionAbstract.java:424)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:624)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.g(IdeKeyEventDispatcher.java:479)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Could you please help?

**Comment by tgamanov** [comment]
Same issue
PhpStorm 2017.3.3
Build #PS-173.4301.34, built on January 18, 2018
Licensed to Smile

JRE: 1.8.0_152-release-1024-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-32-generic

magicento v1.7.0
alm + m
 gives
Argument 2 for @NotNull parameter of com/magicento2/extensions/intention/Magicento2IntentionAbstract.isAvailable must not be null

Argument 2 for @NotNull parameter of com/magicento2/extensions/intention/Magicento2IntentionAbstract.isAvailable must not be null
java.lang.IllegalArgumentException: Argument 2 for @NotNull parameter of com/magicento2/extensions/intention/Magicento2IntentionAbstract.isAvailable must not be null
	at com.magicento2.extensions.intention.Magicento2IntentionAbstract.isAvailable(Magicento2IntentionAbstract.java)
	at com.magicento2.actions.IntentionAbstractAction._isApplicable(IntentionAbstractAction.java:32)
	at com.magicento2.actions.Magicento2ActionAbstract.isApplicable(Magicento2ActionAbstract.java:76)
	at com.magicento2.Magicento2Action._getMagentoContextActions(Magicento2Action.java:135)
	at com.magicento2.Magicento2Action.executeAction(Magicento2Action.java:37)
	at com.magicento2.actions.Magicento2ActionAbstract.actionPerformed(Magicento2ActionAbstract.java:424)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:624)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.g(IdeKeyEventDispatcher.java:479)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


java.lang.IllegalArgumentException: Argument 2 for @NotNull parameter of com/magicento2/extensions/intention/Magicento2IntentionAbstract.isAvailable must not be null
	at com.magicento2.extensions.intention.Magicento2IntentionAbstract.isAvailable(Magicento2IntentionAbstract.java)
	at com.magicento2.actions.IntentionAbstractAction._isApplicable(IntentionAbstractAction.java:32)
	at com.magicento2.actions.Magicento2ActionAbstract.isApplicable(Magicento2ActionAbstract.java:76)
	at com.magicento2.Magicento2Action._getMagentoContextActions(Magicento2Action.java:135)
	at com.magicento2.Magicento2Action.executeAction(Magicento2Action.java:37)
	at com.magicento2.actions.Magicento2ActionAbstract.actionPerformed(Magicento2ActionAbstract.java:424)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:624)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.g(IdeKeyEventDispatcher.java:479)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


java.lang.IllegalArgumentException: Argument 2 for @NotNull parameter of com/magicento2/extensions/intention/Magicento2IntentionAbstract.isAvailable must not be null
	at com.magicento2.extensions.intention.Magicento2IntentionAbstract.isAvailable(Magicento2IntentionAbstract.java)
	at com.magicento2.actions.IntentionAbstractAction._isApplicable(IntentionAbstractAction.java:32)
	at com.magicento2.actions.Magicento2ActionAbstract.isApplicable(Magicento2ActionAbstract.java:76)
	at com.magicento2.Magicento2Action._getMagentoContextActions(Magicento2Action.java:135)
	at com.magicento2.Magicento2Action.executeAction(Magicento2Action.java:37)
	at com.magicento2.actions.Magicento2ActionAbstract.actionPerformed(Magicento2ActionAbstract.java:424)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:624)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.g(IdeKeyEventDispatcher.java:479)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


java.lang.IllegalArgumentException: Argument 2 for @NotNull parameter of com/magicento2/extensions/intention/Magicento2IntentionAbstract.isAvailable must not be null
	at com.magicento2.extensions.intention.Magicento2IntentionAbstract.isAvailable(Magicento2IntentionAbstract.java)
	at com.magicento2.actions.IntentionAbstractAction._isApplicable(IntentionAbstractAction.java:32)
	at com.magicento2.actions.Magicento2ActionAbstract.isApplicable(Magicento2ActionAbstract.java:76)
	at com.magicento2.Magicento2Action._getMagentoContextActions(Magicento2Action.java:135)
	at com.magicento2.Magicento2Action.executeAction(Magicento2Action.java:37)
	at com.magicento2.actions.Magicento2ActionAbstract.actionPerformed(Magicento2ActionAbstract.java:424)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:624)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.g(IdeKeyEventDispatcher.java:479)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Invalidate cache/restart does not help.

**Comment by TristanCICT** [comment]
Same here!

**Comment by tobiasteatox** [comment]
I have a similar problem here. At first i thought the plugin is not working - but now i found out that this error occurs only if i hit the shortcut alt+m in editor while the pointer is behind the last character of a file. 

If you need the full error message let me know, but i looked similar to the message above. 

![position](https://user-images.githubusercontent.com/11499557/35978401-df10bef2-0ce5-11e8-9c98-1ed5b9e62714.png)

**Comment by Koc** [comment]
@enriquepiatti any chance to update plugin for getting support of the latest stable PS versions?

**Comment by enriquepiatti** [comment]
Hi, yes @tobiasteatox, thanks for pointing it, that seems to be the problem.
I have uploaded a new version (v1.7.1) with a fix to work even when cursor is at EOF.
But if you don't want to update, just put the cursor somewhere else before using ALT+M
