### ISSUE TITLE
Permanently get plugin error

### ISSUE THREAD

**Issue by vaso123** [enriquepiatti/Magicento#289]
`null
java.lang.NullPointerException
	at java.net.URLEncoder.encode(URLEncoder.java:204)
	at com.magicento2.helpers.JavaHelper$4$1$1.run(JavaHelper.java:293)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

java.lang.NullPointerException
	at com.magicento2.models.user.Magicento2LocalUser.loadComplete(Magicento2LocalUser.java:143)
	at com.magicento2.models.user.ModelDb$1.doSomethingWithResult(ModelDb.java:42)
	at com.magicento2.helpers.JavaHelper$4$1$2.run(JavaHelper.java:403)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2771)
	at com.magicento2.helpers.JavaHelper$4$1.finished(JavaHelper.java:400)
	at com.intellij.util.concurrency.SwingWorker.lambda$new$0(SwingWorker.java:146)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

`

**Comment by enriquepiatti** [comment]
Hi @vaso123 were you able to validate your Magicento2 license? is this error blocking the plugin?

**Comment by vaso123** [comment]
I did not see that button, because my window was lower. It should be under the input not beside.

Anyway, I do not know. I pushed the Validate button, it was disabled for a while, then enabled again and nothing happened.

I am still getting the errors, so I think, no.

**Comment by enriquepiatti** [comment]
Please contact me by email and send me a screenshot showing your Magicento settings.
