### ISSUE TITLE
Argument 1 for @NotNull parameter of ... LookupElementBuilder.create must not be null

### ISSUE THREAD

**Issue by Schrank** [enriquepiatti/Magicento#30]
Argument 1 for @NotNull parameter of com/intellij/codeInsight/lookup/LookupElementBuilder.create must not be null: Argument 1 for @NotNull parameter of com/intellij/codeInsight/lookup/LookupElementBuilder.create must not be null
java.lang.IllegalArgumentException: Argument 1 for @NotNull parameter of com/intellij/codeInsight/lookup/LookupElementBuilder.create must not be null
    at com.intellij.codeInsight.lookup.LookupElementBuilder.create(LookupElementBuilder.java)
    at com.magicento.extensions.MagicentoPhpCompletionContributor.getAutocompleteForFactory(MagicentoPhpCompletionContributor.java:329)
    at com.magicento.extensions.MagicentoPhpCompletionContributor$1.addCompletions(MagicentoPhpCompletionContributor.java:79)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:154)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
    at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:115)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:748)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$900(CompletionProgressIndicator.java:85)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:730)
    at com.intellij.codeInsight.completion.AsyncCompletion$1$1$1.run(CompletionThreading.java:93)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:935)
    at com.intellij.codeInsight.completion.AsyncCompletion$1$1.run(CompletionThreading.java:88)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:191)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:232)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:181)
    at com.intellij.codeInsight.completion.AsyncCompletion$1.run(CompletionThreading.java:84)
    at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:465)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:153)

**Comment by Schrank** [comment]
Don't ask me, what I did...
