### ISSUE TITLE
Error when trying to rewrite class Mage_Eav_Model_Entity_Setup

### ISSUE THREAD

**Issue by pastanislas** [enriquepiatti/Magicento#33]
Working with other classes but when I try to rewrite   class Mage_Eav_Model_Entity_Setup I get the following Java exception :

Error during dispatching of java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.intellij.openapi.util.EdtRunnable$1@1caa9b8,notifier=null,catchExceptions=false,when=1358846342025] on sun.awt.windows.WToolkit@1b8d6f7: String index out of range: -1

Below the full error log. Thank you for your Amazing work :)

Error during dispatching of java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.intellij.openapi.util.EdtRunnable$1@1caa9b8,notifier=null,catchExceptions=false,when=1358846342025] on sun.awt.windows.WToolkit@1b8d6f7: String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(String.java:1937)
    at java.lang.String.substring(String.java:1904)
    at com.magicento.actions.RewriteClassAction.executeAction(RewriteClassAction.java:90)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:359)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:638)
    at com.intellij.ui.popup.AbstractPopup$18.run(AbstractPopup.java:1219)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:616)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:597)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:567)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:55)
    at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:102)
    at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:646)
    at java.awt.EventQueue.access$000(EventQueue.java:84)
    at java.awt.EventQueue$1.run(EventQueue.java:607)
    at java.awt.EventQueue$1.run(EventQueue.java:605)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:616)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:718)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:543)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:421)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:379)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by ghost** [comment]
I also get a similar error when trying to rewrite: Mage_Usa_Model_Shipping_Carrier_Ups

**Comment by enriquepiatti** [comment]
Fixed in v1.6.0
