### ISSUE TITLE
Not working with PHPStorm 5

### ISSUE THREAD

**Issue by madsamurai** [enriquepiatti/Magicento#4]
Hi, this looks extremely helpful, but I can't get it to go on PHPStorm 5 (seems to be the only version available from them). Errors below when I launch PHPStorm. OSX 10.7.4, PHPStorm v5.0.1, JDK 1.6.0_35

Thanks, really looking forward to trying this out!
-Chad

Error while registering component: com.intellij.openapi.components.OldComponentConfig@548c491e: com.magicento.MagicentoProjectComponent PluginClassLoader[Magicento, 0.6] [Plugin: Magicento]
com.intellij.diagnostic.PluginException: com.magicento.MagicentoProjectComponent PluginClassLoader[Magicento, 0.6] [Plugin: Magicento]
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:463)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:436)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.access$000(ComponentManagerImpl.java:422)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:102)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.initComponents(ComponentManagerImpl.java:347)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:86)
    at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:307)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:278)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:331)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.access$400(ProjectManagerImpl.java:81)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$9.compute(ProjectManagerImpl.java:546)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$9.compute(ProjectManagerImpl.java:542)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$4.run(ProgressManagerImpl.java:259)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:472)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$6.run(ProgressManagerImpl.java:291)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:181)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:221)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:172)
    at com.intellij.openapi.application.impl.ApplicationImpl$8$1.run(ApplicationImpl.java:684)
    at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:457)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:148)
Caused by: java.lang.ClassNotFoundException: com.magicento.MagicentoProjectComponent PluginClassLoader[Magicento, 0.6]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:446)
    ... 26 more

and then:

class with name "com.magicento.MagicentoAction" not found [Plugin: Magicento]: class with name "com.magicento.MagicentoAction" not found [Plugin: Magicento]
com.intellij.diagnostic.PluginException: class with name "com.magicento.MagicentoAction" not found [Plugin: Magicento]
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:255)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:226)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:219)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.unstub(DefaultActionGroup.java:261)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:240)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1154)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1148)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:947)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:1148)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:1162)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1142)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.d(ActionManagerImpl.java:1134)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.access$200(ActionManagerImpl.java:72)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$4.run(ActionManagerImpl.java:1117)
    at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:457)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:148)
Caused by: java.lang.ClassNotFoundException: com.magicento.MagicentoAction PluginClassLoader[Magicento, 0.6]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:248)
    ... 21 more

**Comment by enriquepiatti** [comment]
That's weird, I've tested it in PHPStorm 5 and it worked fine, maybe it's related with the OSX version (I've tested the windows version).
I'll ask to jetbrains about this.

**Comment by enriquepiatti** [comment]
Chad, can you make more tests about this? maybe trying to uninstall and reinstall again the plugin etc. Because I've tested it on OSX 10.8.1 and it works too.

**Comment by madsamurai** [comment]
Hi, I just ran the updater to 0.0.8 and it seems to be working now. Thanks!

**Comment by madsamurai** [comment]
Of course, now I'm not sure how to make it go... Is there a guide available for basic setup? I found the magicento settings, but not sure what some of them are as they are shortened:
Absolute path to app/Ma...
Absolute path to php int...
Also are these absolute paths based on file system or local dev url?
Thanks again,
Chad

**Comment by enriquepiatti** [comment]
I don't know why you are seeing the labels shortened, anyway the full text is:
Absolute Path to Mage.php: here you should put the file path to Mage.php of your magento project.
Absolute Path to PHP Interpreter: you can leave this empty if you can run "php" from anywhere
