### ISSUE TITLE
Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by meabed** [enriquepiatti/Magicento#40]
com/magicento/MagicentoProjectComponent : Unsupported major.minor version 51.0 [Plugin: Magicento]: com/magicento/MagicentoProjectComponent : Unsupported major.minor version 51.0 [Plugin: Magicento]
com.intellij.diagnostic.PluginException: com/magicento/MagicentoProjectComponent : Unsupported major.minor version 51.0 [Plugin: Magicento]
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:108)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:445)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:435)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.access$000(ComponentManagerImpl.java:421)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:102)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.initComponents(ComponentManagerImpl.java:346)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:86)
    at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:307)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:282)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.access$400(ProjectManagerImpl.java:82)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$10.compute(ProjectManagerImpl.java:562)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$10.compute(ProjectManagerImpl.java:558)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$4.run(ProgressManagerImpl.java:269)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:495)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$6.run(ProgressManagerImpl.java:304)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:185)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:226)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:175)
    at com.intellij.openapi.application.impl.ApplicationImpl$9$1.run(ApplicationImpl.java:676)
    at com.intellij.openapi.application.impl.ApplicationImpl$7.run(ApplicationImpl.java:449)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:152)
Caused by: java.lang.UnsupportedClassVersionError: com/magicento/MagicentoProjectComponent : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:150)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:146)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:122)
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:102)
    ... 30 more

**Comment by mlopes** [comment]
Having the same issue since I upgraded to version 1.4.0 yesterday. I'm using PHPStorm 6.0 build #PS-127.100 with 64 bit JDK 1.6.0_43 on Mac OS X 10.7.5.

**Comment by knowj** [comment]
Same issue:
PHP Storm 6.0
Build: #PS127.100
JDK 1.6.0_43
OSX 10.8.3 i7

**Comment by therouv** [comment]
Any update on this?

**Comment by enriquepiatti** [comment]
Fixed in 1.4.2, please update.
