### ISSUE TITLE
Error after updating to 1.4.1

### ISSUE THREAD

**Issue by danmshields** [enriquepiatti/Magicento#41]
I updated again when I saw there was an update for the previous issues after you updated for the new Meta stuff.

Error during dispatching of 

java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.intellij.openapi.util.EdtRunnable$1@47c49dc1,notifier=null,catchExceptions=false,when=1365542136104] on sun.awt.X11.XToolkit@1e88364: Argument 1 for @NotNull parameter of com/intellij/psi/impl/PsiFileFactoryImpl.createFileFromText must not be null
java.lang.IllegalArgumentException: Argument 1 for @NotNull parameter of com/intellij/psi/impl/PsiFileFactoryImpl.createFileFromText must not be null
at com.intellij.psi.impl.PsiFileFactoryImpl.createFileFromText(PsiFileFactoryImpl.java)
at com.magicento.helpers.FileHelper$3.run(FileHelper.java:226)
at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1013)
at com.magicento.helpers.FileHelper.createPsiFile(FileHelper.java:199)
at com.magicento.models.PhpStormMetaNamespace.savePhpStormMetaFile(PhpStormMetaNamespace.java:60)
at com.magicento.models.PhpStormMetaNamespace.savePhpStormMetaFile(PhpStormMetaNamespace.java:80)
at com.magicento.actions.CreatePhpStormMetaNamespaceAction.executeAction(CreatePhpStormMetaNamespaceAction.java:33)
at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:359)
at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:726)
at com.intellij.ui.popup.AbstractPopup$18.run(AbstractPopup.java:1253)
at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:616)
at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:597)
at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:567)
at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:55)
at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:102)
at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:641)
at java.awt.EventQueue.access$000(EventQueue.java:84)
at java.awt.EventQueue$1.run(EventQueue.java:602)
at java.awt.EventQueue$1.run(EventQueue.java:600)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:611)
at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:686)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:511)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:334)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by enriquepiatti** [comment]
Seems like the content for the PHPSTORM_META namespace is empty, I have added an extra check for that (v1.4.2) situation, but I can't imagine why is that happening, could you provide more information if you can reproduce the error?

**Comment by enriquepiatti** [comment]
From v1.6.0 we don't need to generate the PHPSTORM META file anymore, everything is done automatically.
