### ISSUE TITLE
Error on invocation of 'create PHPSTORMMETA namespace'

### ISSUE THREAD

**Issue by EliezerIsrael** [enriquepiatti/Magicento#45]
I have a new installation, as of two days ago, of PHP Storm 6.0 - build 127.1
Installed Magicento.

On invocation of 'create PHPSTORMMETA namespace', I get this in the console:

1:51:37 PM IllegalArgumentException: Error during dispatching of java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.intellij.openapi.util.EdtRunnable$1@765746ca,notifier=null,catchExceptions=false,when=1366195897678] on apple.awt.CToolkit@1babe751: Argument 1 for @NotNull parameter of com/intellij/psi/impl/PsiFileFactoryImpl.createFileFromText must not be null

**Comment by enriquepiatti** [comment]
Hi Eliezer, please could you past the full trace for that error?
Remember you need the last PHPStorm version for using that feature (http://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Early+Access+Program or http://blog.jetbrains.com/phpstorm/2013/04/phpstorm-6-0-1-released/), what version of Magicento are you using? 
Anyway, I'm planning to release a new Magicento version soon which doesn't need to generate the PHPSTORM_META manually.

**Comment by EliezerIsrael** [comment]
Looks like I was on a version that's too early.  
I'm working on the upgrade - running into an independent error.

Here's the full trace of the original issue, in case it's useful to you.

Error during dispatching of java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.intellij.openapi.util.EdtRunnable$1@765746ca,notifier=null,catchExceptions=false,when=1366195897678] on apple.awt.CToolkit@1babe751: Argument 1 for @NotNull parameter of com/intellij/psi/impl/PsiFileFactoryImpl.createFileFromText must not be null
java.lang.IllegalArgumentException: Argument 1 for @NotNull parameter of com/intellij/psi/impl/PsiFileFactoryImpl.createFileFromText must not be null
    at com.intellij.psi.impl.PsiFileFactoryImpl.createFileFromText(PsiFileFactoryImpl.java)
    at com.magicento.helpers.FileHelper$3.run(FileHelper.java:226)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1008)
    at com.magicento.helpers.FileHelper.createPsiFile(FileHelper.java:199)
    at com.magicento.models.PhpStormMetaNamespace.savePhpStormMetaFile(PhpStormMetaNamespace.java:65)
    at com.magicento.models.PhpStormMetaNamespace.savePhpStormMetaFile(PhpStormMetaNamespace.java:85)
    at com.magicento.actions.CreatePhpStormMetaNamespaceAction.executeAction(CreatePhpStormMetaNamespaceAction.java:33)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:359)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:726)
    at com.intellij.ui.popup.AbstractPopup$18.run(AbstractPopup.java:1253)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:616)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:597)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:567)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:55)
    at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:102)
    at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:708)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:669)
    at java.awt.EventQueue$2.run(EventQueue.java:667)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:678)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:685)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:510)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:333)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by EliezerIsrael** [comment]
I still have the issue on 6.0.1.

Error during dispatching of java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.intellij.openapi.util.EdtRunnable$1@3fd48d06,notifier=null,catchExceptions=false,when=1366282908585] on apple.awt.CToolkit@28246ceb: Argument 1 for @NotNull parameter of com/intellij/psi/impl/PsiFileFactoryImpl.createFileFromText must not be null
java.lang.IllegalArgumentException: Argument 1 for @NotNull parameter of com/intellij/psi/impl/PsiFileFactoryImpl.createFileFromText must not be null
    at com.intellij.psi.impl.PsiFileFactoryImpl.createFileFromText(PsiFileFactoryImpl.java)
    at com.magicento.helpers.FileHelper$3.run(FileHelper.java:226)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1013)
    at com.magicento.helpers.FileHelper.createPsiFile(FileHelper.java:199)
    at com.magicento.models.PhpStormMetaNamespace.savePhpStormMetaFile(PhpStormMetaNamespace.java:65)
    at com.magicento.models.PhpStormMetaNamespace.savePhpStormMetaFile(PhpStormMetaNamespace.java:85)
    at com.magicento.actions.CreatePhpStormMetaNamespaceAction.executeAction(CreatePhpStormMetaNamespaceAction.java:33)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:359)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:726)
    at com.intellij.ui.popup.AbstractPopup$18.run(AbstractPopup.java:1253)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:616)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:597)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:567)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:55)
    at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:102)
    at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:708)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:669)
    at java.awt.EventQueue$2.run(EventQueue.java:667)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:678)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:686)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:511)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:334)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by enriquepiatti** [comment]
From v1.6.0 we don't need to generate the PHPSTORM META file anymore, everything is done automatically.
