### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by bennoislost** [enriquepiatti/Magicento#53]
Hi Enrique,

When creating a project in a different directory to your Magento source an IllegalArgumentException is thrown.

To replicate: 
1. Create a blank project in any directory
2. In the project settings remove the current directory then add a directory containing your Magento source.

Mac: OS X 10.8.3
phpStorm: 6.0.2

I've never seen this when creating projects with Magento in the same directory as the project folder...

```
Argument 0 for @NotNull parameter of com/magicento/models/xml/layout/MagentoLayoutXml.getAllActiveXmlLayoutNames must not be null: Argument 0 for @NotNull parameter of com/magicento/models/xml/layout/MagentoLayoutXml.getAllActiveXmlLayoutNames must not be null
java.lang.IllegalArgumentException: Argument 0 for @NotNull parameter of com/magicento/models/xml/layout/MagentoLayoutXml.getAllActiveXmlLayoutNames must not be null
    at com.magicento.models.xml.layout.MagentoLayoutXml.getAllActiveXmlLayoutNames(MagentoLayoutXml.java)
    at com.magicento.models.xml.layout.MagentoLayoutXml.getMergedXml(MagentoLayoutXml.java:98)
    at com.magicento.models.xml.MagentoXml.getMergedXmlFile(MagentoXml.java:267)
    at com.magicento.MagicentoProjectComponent.getCachedLayoutXml(MagicentoProjectComponent.java:133)
    at com.magicento.models.layout.Template.getBlockElements(Template.java:61)
    at com.magicento.models.layout.Template.getBlocksClasses(Template.java:128)
    at com.magicento.extensions.BlockTypeProvider.getType(BlockTypeProvider.java:60)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:46)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:41)
    at com.intellij.openapi.util.Computable$NotNullCachedComputable.compute(Computable.java:52)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:110)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:41)
    at com.jetbrains.php.codeInsight.typeInference.PhpTypeInferenceUtil.getInferredType(PhpTypeInferenceUtil.java:208)
    at com.jetbrains.php.codeInsight.typeInference.PhpTypeInferenceUtil.getType(PhpTypeInferenceUtil.java:198)
    at com.jetbrains.php.codeInsight.typeInference.PhpTypeInferenceUtil.getType(PhpTypeInferenceUtil.java:189)
    at com.jetbrains.php.lang.psi.elements.impl.VariableImpl.getType(VariableImpl.java:590)
    at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.resolveGlobal(MemberReferenceImpl.java:123)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:106)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:103)
    at com.intellij.psi.impl.source.resolve.ResolveCache$2.compute(ResolveCache.java:107)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:110)
    at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:104)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:132)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:124)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.multiResolve(PhpReferenceImpl.java:98)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.resolve(PhpReferenceImpl.java:85)
    at com.jetbrains.php.lang.annotator.PhpAnnotatorVisitor.checkAccessModifiers(PhpAnnotatorVisitor.java:310)
    at com.jetbrains.php.lang.annotator.PhpAnnotatorVisitor.visitPhpMethodReference(PhpAnnotatorVisitor.java:293)
    at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:31)
    at com.jetbrains.php.lang.annotator.PhpAnnotator.annotate(PhpAnnotator.java:17)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:160)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:103)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$10.run(GeneralHighlightingPass.java:644)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:757)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$3500(GeneralHighlightingPass.java:83)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$12.run(GeneralHighlightingPass.java:763)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:760)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:717)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:208)
    at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:58)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:357)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1182)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:348)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:226)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:345)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:321)
    at com.intellij.concurrency.JobLauncherImpl$3.call(JobLauncherImpl.java:145)
    at com.intellij.concurrency.JobLauncherImpl$3.call(JobLauncherImpl.java:142)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)



java.lang.IllegalArgumentException: Argument 0 for @NotNull parameter of com/magicento/models/xml/layout/MagentoLayoutXml.getAllActiveXmlLayoutNames must not be null
    at com.magicento.models.xml.layout.MagentoLayoutXml.getAllActiveXmlLayoutNames(MagentoLayoutXml.java)
    at com.magicento.models.xml.layout.MagentoLayoutXml.getMergedXml(MagentoLayoutXml.java:98)
    at com.magicento.models.xml.MagentoXml.getMergedXmlFile(MagentoXml.java:267)
    at com.magicento.MagicentoProjectComponent.getCachedLayoutXml(MagicentoProjectComponent.java:133)
    at com.magicento.models.layout.Template.getBlockElements(Template.java:61)
    at com.magicento.models.layout.Template.getBlocksClasses(Template.java:128)
    at com.magicento.extensions.BlockTypeProvider.getType(BlockTypeProvider.java:60)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:46)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:41)
    at com.intellij.openapi.util.Computable$NotNullCachedComputable.compute(Computable.java:52)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:110)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:41)
    at com.jetbrains.php.codeInsight.typeInference.PhpTypeInferenceUtil.getInferredType(PhpTypeInferenceUtil.java:208)
    at com.jetbrains.php.codeInsight.typeInference.PhpTypeInferenceUtil.getType(PhpTypeInferenceUtil.java:198)
    at com.jetbrains.php.codeInsight.typeInference.PhpTypeInferenceUtil.getType(PhpTypeInferenceUtil.java:189)
    at com.jetbrains.php.lang.psi.elements.impl.VariableImpl.getType(VariableImpl.java:590)
    at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.getSignature(MemberReferenceImpl.java:164)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeAnalyserVisitor.visitPhpReference(PhpTypeAnalyserVisitor.java:78)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeAnalyserVisitor.visitPhpMethodReference(PhpTypeAnalyserVisitor.java:399)
    at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:31)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:51)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:41)
    at com.intellij.openapi.util.Computable$NotNullCachedComputable.compute(Computable.java:52)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:110)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:41)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:23)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.getType(PhpReferenceImpl.java:152)
    at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection.analyzeCall(PhpVoidFunctionResultUsedInspection.java:47)
    at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection.access$000(PhpVoidFunctionResultUsedInspection.java:21)
    at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection$1.visitPhpMethodReference(PhpVoidFunctionResultUsedInspection.java:39)
    at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:31)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.acceptElements(LocalInspectionsPass.java:412)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.createVisitorAndAcceptElements(LocalInspectionsPass.java:370)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.doVisitElement(LocalInspectionsPass.java:341)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$000(LocalInspectionsPass.java:78)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:309)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:306)
    at com.intellij.concurrency.JobLauncherImpl$2$1.run(JobLauncherImpl.java:115)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:226)
    at com.intellij.concurrency.JobLauncherImpl$2.process(JobLauncherImpl.java:113)
    at com.intellij.concurrency.JobLauncherImpl$1.run(JobLauncherImpl.java:54)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1182)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:97)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)



java.lang.IllegalArgumentException: Argument 0 for @NotNull parameter of com/magicento/models/xml/layout/MagentoLayoutXml.getAllActiveXmlLayoutNames must not be null
    at com.magicento.models.xml.layout.MagentoLayoutXml.getAllActiveXmlLayoutNames(MagentoLayoutXml.java)
    at com.magicento.models.xml.layout.MagentoLayoutXml.getMergedXml(MagentoLayoutXml.java:98)
    at com.magicento.models.xml.MagentoXml.getMergedXmlFile(MagentoXml.java:267)
    at com.magicento.MagicentoProjectComponent.getCachedLayoutXml(MagicentoProjectComponent.java:133)
    at com.magicento.models.layout.Template.getBlockElements(Template.java:61)
    at com.magicento.models.layout.Template.getBlocksClasses(Template.java:128)
    at com.magicento.extensions.BlockTypeProvider.getType(BlockTypeProvider.java:60)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:46)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:41)
    at com.intellij.openapi.util.Computable$NotNullCachedComputable.compute(Computable.java:52)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:110)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:41)
    at com.jetbrains.php.codeInsight.typeInference.PhpTypeInferenceUtil.getInferredType(PhpTypeInferenceUtil.java:208)
    at com.jetbrains.php.codeInsight.typeInference.PhpTypeInferenceUtil.getType(PhpTypeInferenceUtil.java:198)
    at com.jetbrains.php.codeInsight.typeInference.PhpTypeInferenceUtil.getType(PhpTypeInferenceUtil.java:189)
    at com.jetbrains.php.lang.psi.elements.impl.VariableImpl.getType(VariableImpl.java:590)
    at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.resolveGlobal(MemberReferenceImpl.java:123)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:106)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:103)
    at com.intellij.psi.impl.source.resolve.ResolveCache$2.compute(ResolveCache.java:107)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:110)
    at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:104)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:132)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:124)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.multiResolve(PhpReferenceImpl.java:98)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.resolve(PhpReferenceImpl.java:85)
    at com.jetbrains.php.lang.annotator.PhpAnnotatorVisitor.checkAccessModifiers(PhpAnnotatorVisitor.java:310)
    at com.jetbrains.php.lang.annotator.PhpAnnotatorVisitor.visitPhpMethodReference(PhpAnnotatorVisitor.java:293)
    at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:31)
    at com.jetbrains.php.lang.annotator.PhpAnnotator.annotate(PhpAnnotator.java:17)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:160)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:103)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$10.run(GeneralHighlightingPass.java:644)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:757)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$3500(GeneralHighlightingPass.java:83)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$12.run(GeneralHighlightingPass.java:763)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:760)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:717)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:208)
    at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:58)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:357)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1182)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:348)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:226)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:345)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:321)
    at com.intellij.concurrency.JobLauncherImpl$3.call(JobLauncherImpl.java:145)
    at com.intellij.concurrency.JobLauncherImpl$3.call(JobLauncherImpl.java:142)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)



java.lang.IllegalArgumentException: Argument 0 for @NotNull parameter of com/magicento/models/xml/layout/MagentoLayoutXml.getAllActiveXmlLayoutNames must not be null
    at com.magicento.models.xml.layout.MagentoLayoutXml.getAllActiveXmlLayoutNames(MagentoLayoutXml.java)
    at com.magicento.models.xml.layout.MagentoLayoutXml.getMergedXml(MagentoLayoutXml.java:98)
    at com.magicento.models.xml.MagentoXml.getMergedXmlFile(MagentoXml.java:267)
    at com.magicento.MagicentoProjectComponent.getCachedLayoutXml(MagicentoProjectComponent.java:133)
    at com.magicento.models.layout.Template.getBlockElements(Template.java:61)
    at com.magicento.models.layout.Template.getBlocksClasses(Template.java:128)
    at com.magicento.extensions.BlockTypeProvider.getType(BlockTypeProvider.java:60)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:46)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:41)
    at com.intellij.openapi.util.Computable$NotNullCachedComputable.compute(Computable.java:52)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:110)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:41)
    at com.jetbrains.php.codeInsight.typeInference.PhpTypeInferenceUtil.getInferredType(PhpTypeInferenceUtil.java:208)
    at com.jetbrains.php.codeInsight.typeInference.PhpTypeInferenceUtil.getType(PhpTypeInferenceUtil.java:198)
    at com.jetbrains.php.codeInsight.typeInference.PhpTypeInferenceUtil.getType(PhpTypeInferenceUtil.java:189)
    at com.jetbrains.php.lang.psi.elements.impl.VariableImpl.getType(VariableImpl.java:590)
    at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.getSignature(MemberReferenceImpl.java:164)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeAnalyserVisitor.visitPhpReference(PhpTypeAnalyserVisitor.java:78)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeAnalyserVisitor.visitPhpMethodReference(PhpTypeAnalyserVisitor.java:399)
    at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:31)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:51)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:41)
    at com.intellij.openapi.util.Computable$NotNullCachedComputable.compute(Computable.java:52)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:110)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:41)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:23)
    at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.getType(PhpReferenceImpl.java:152)
    at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection.analyzeCall(PhpVoidFunctionResultUsedInspection.java:47)
    at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection.access$000(PhpVoidFunctionResultUsedInspection.java:21)
    at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection$1.visitPhpMethodReference(PhpVoidFunctionResultUsedInspection.java:39)
    at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:31)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.acceptElements(LocalInspectionsPass.java:412)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.createVisitorAndAcceptElements(LocalInspectionsPass.java:370)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.doVisitElement(LocalInspectionsPass.java:341)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$000(LocalInspectionsPass.java:78)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:309)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:306)
    at com.intellij.concurrency.JobLauncherImpl$2$1.run(JobLauncherImpl.java:115)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:226)
    at com.intellij.concurrency.JobLauncherImpl$2.process(JobLauncherImpl.java:113)
    at com.intellij.concurrency.JobLauncherImpl$1.run(JobLauncherImpl.java:54)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1182)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:97)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)

```

**Comment by enriquepiatti** [comment]
Magicento doesn't support that at the moment.
Why are you using a different folder for your Magento? (this happened to me for example when I worked with external libraries...).
Anyway, I will fix the error so at least you don't get those exceptions.

**Comment by bennoislost** [comment]
Just a vanity thing really! I wanted to keep the project meta separate from source code.. no worries thanks for the update.

**Comment by enriquepiatti** [comment]
I think this should work with Magicento v2.1.0
