### ISSUE TITLE
Exception right after IDE start (or change in the template settings?)

### ISSUE THREAD

**Issue by Schrank** [enriquepiatti/Magicento#64]
I got the following exception right after I changed the template project settings (close all windows, get the project list, click on Configure and change magicento settings, e.g. Enabled -> false

Cannot find MagicentoProjectComponent instance (if you think this is a bug please send the trace to issues@magicento.com)
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:54)
    at com.magicento.helpers.IdeHelper.logError(IdeHelper.java:67)
    at com.magicento.MagicentoSettings.getDefaultPathToMagento(MagicentoSettings.java:122)
    at com.magicento.MagicentoSettings.autoSetPathToMage(MagicentoSettings.java:95)
    at com.magicento.MagicentoSettings.getInstance(MagicentoSettings.java:68)
    at com.magicento.ui.forms.MagicentoSettingsForm.isModified(MagicentoSettingsForm.java:262)
    at com.intellij.openapi.options.newEditor.OptionsEditor.i(OptionsEditor.java:570)
    at com.intellij.openapi.options.newEditor.OptionsEditor.g(OptionsEditor.java:559)
    at com.intellij.openapi.options.newEditor.OptionsEditor.e(OptionsEditor.java:514)
    at com.intellij.openapi.options.newEditor.OptionsEditor.d(OptionsEditor.java:506)
    at com.intellij.openapi.options.newEditor.OptionsEditor.access$2300(OptionsEditor.java:68)
    at com.intellij.openapi.options.newEditor.OptionsEditor$8.runEdt(OptionsEditor.java:376)
    at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
    at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:1971)
    at com.intellij.openapi.util.EdtRunnable.run(EdtRunnable.java:25)
    at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:54)
    at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:62)
    at com.intellij.openapi.util.ActionCallback$1.run(ActionCallback.java:172)
    at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:54)
    at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:62)
    at com.intellij.openapi.options.newEditor.OptionsEditor$10.run(OptionsEditor.java:469)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:708)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:669)
    at java.awt.EventQueue$2.run(EventQueue.java:667)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:678)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:700)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:525)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:205)
    at java.awt.Dialog$1.run(Dialog.java:1049)
    at java.awt.Dialog$3.run(Dialog.java:1101)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.awt.Dialog.show(Dialog.java:1099)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:706)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:399)
    at com.intellij.openapi.ui.DialogWrapper.showAndGetOk(DialogWrapper.java:1460)
    at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1435)
    at com.intellij.ide.actions.ShowSettingsUtilImpl.a(ShowSettingsUtilImpl.java:64)
    at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:51)
    at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:57)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:151)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:169)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:132)
    at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:310)
    at java.awt.Component.processEvent(Component.java:6147)
    at java.awt.Container.processEvent(Container.java:2083)
    at java.awt.Component.dispatchEventImpl(Component.java:4744)
    at java.awt.Container.dispatchEventImpl(Container.java:2141)
    at java.awt.Component.dispatchEvent(Component.java:4572)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4619)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4280)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4210)
    at java.awt.Container.dispatchEventImpl(Container.java:2127)
    at java.awt.Window.dispatchEventImpl(Window.java:2489)
    at java.awt.Component.dispatchEvent(Component.java:4572)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:710)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:669)
    at java.awt.EventQueue$2.run(EventQueue.java:667)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:683)
    at java.awt.EventQueue$3.run(EventQueue.java:681)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:680)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:700)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:521)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by enriquepiatti** [comment]
I didn't understand very well when this happens. 
Are you still seeing this bug?

**Comment by Schrank** [comment]
No, I can't reproduce it :)

**Comment by Schrank** [comment]
Exception is back. Don't ask me how it occured - no idea :-/

I'm running on Version 2.0.0 and PHPStorm 6.0.3 (129.814)

```
Cannot find MagicentoProjectComponent instance (if you think this is a bug please send the trace to issues@magicento.com)
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:54)
    at com.magicento.helpers.IdeHelper.logError(IdeHelper.java:79)
    at com.magicento.MagicentoSettings.getDefaultPathToMagento(MagicentoSettings.java:140)
    at com.magicento.MagicentoSettings.getDefaultPathToMagento(MagicentoSettings.java:149)
    at com.magicento.MagicentoSettings.getDefaultPathToMagento(MagicentoSettings.java:133)
    at com.magicento.MagicentoSettings.autoSetPathToMage(MagicentoSettings.java:113)
    at com.magicento.MagicentoSettings.loadState(MagicentoSettings.java:106)
    at com.magicento.MagicentoSettings.loadState(MagicentoSettings.java:19)
    at com.intellij.openapi.components.impl.stores.ComponentStoreImpl.a(ComponentStoreImpl.java:291)
    at com.intellij.openapi.components.impl.stores.ComponentStoreImpl.access$000(ComponentStoreImpl.java:44)
    at com.intellij.openapi.components.impl.stores.ComponentStoreImpl$1.run(ComponentStoreImpl.java:84)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:929)
    at com.intellij.openapi.components.impl.stores.ComponentStoreImpl.initComponent(ComponentStoreImpl.java:81)
    at com.intellij.openapi.components.impl.stores.DefaultProjectStoreImpl.initComponent(DefaultProjectStoreImpl.java:38)
    at com.intellij.openapi.project.impl.ProjectImpl.initializeComponent(ProjectImpl.java:214)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.initializeInstance(ServiceManagerImpl.java:164)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter$1.compute(ServiceManagerImpl.java:147)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:950)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:139)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:242)
    at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:229)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
    at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.getComponentInstance(AbstractDelegatingMutablePicoContainer.java:75)
    at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:40)
    at com.magicento.MagicentoSettings.getInstance(MagicentoSettings.java:75)
    at com.magicento.ui.forms.MagicentoSettingsForm.createComponent(MagicentoSettingsForm.java:194)
    at com.intellij.openapi.options.newEditor.OptionsEditor$Simple.<init>(OptionsEditor.java:1270)
    at com.intellij.openapi.options.newEditor.OptionsEditor.b(OptionsEditor.java:455)
    at com.intellij.openapi.options.newEditor.OptionsEditor.access$2500(OptionsEditor.java:68)
    at com.intellij.openapi.options.newEditor.OptionsEditor$9$1$1.run(OptionsEditor.java:424)
    at com.intellij.openapi.application.impl.ApplicationImpl.runEdtSafeAction(ApplicationImpl.java:1130)
    at com.intellij.openapi.options.newEditor.OptionsEditor$9$1.run(OptionsEditor.java:418)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:940)
    at com.intellij.openapi.options.newEditor.OptionsEditor$9.run(OptionsEditor.java:416)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:454)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:152)

```

**Comment by enriquepiatti** [comment]
This happens to me when I try to access the Settings without opening any project (close all your projects, and go to settings from the main window).
Is this blocking the IDE or Magicento in some way?
I will remove that check and error log, I think is not useful anymore.

**Comment by Schrank** [comment]
No, it only opens a window (but I think this behaviour is EAP only?)

**Comment by enriquepiatti** [comment]
what do you mean with EAP only?

**Comment by Schrank** [comment]
EAP = Early Access Programm, the beta versions from PHPStorm. And I mean, that if you use the stable versions, the exceptions are catched and not shown to the user.

It does not block the IDE.
It only opens a windows, that an exception was thrown (I think - or does the window only open, if I click on the link in the log? I'm not sure)

**Comment by enriquepiatti** [comment]
but you said you were using PHPStorm 6.0.3 (129.814), that's not an EAP version. Anyway I think you won't see this error anymore in v2.2.0 (it's available to download now, you will see a notification when you open PhpStorm, I will send some emails too just in case).

**Comment by Schrank** [comment]
Oh you are right. The first time it was 6.0.3, because it was the newest "EAP", meanwhile I changed to 130.1197(?) and the exceltion was thrown.

I couldn't reproduce the error on the latest EAP, but whatever you fixed, thanks :-)

Am 20.07.2013 um 15:49 schrieb Enrique Piatti notifications@github.com:
