### ISSUE TITLE
Magicento Menu on PHPStorm v6.0.3

### ISSUE THREAD

**Issue by ghost** [enriquepiatti/Magicento#77]
Hi,

I performed a fresh installation of PHPStorm V6.0.3 and installed Magicento Plugin V2.0.0. On restart of the IDE, I get message to update Magicento to latest version by pressing Alt + M. However when I do that, nothing happens. I checked Magicento Menu from PHPStorm Tools submenu and Magicento (Alt+M) is disabled.

Can you please help?

**Comment by enriquepiatti** [comment]
Magicento menu (ALT + M) only works when you are editing some file, please open some Magento project (where you can enable Magicento if it isn't), open some file (any file) and with the cursor inside the Editor press ALT + M.
Let me know if that works (y)

**Comment by ghost** [comment]
Hi,

I was trying to access the menu option without having an open file.

Thanks for your fast response!

Bye.

**Comment by Schrank** [comment]
I tried it with an open file :)

```
null
java.lang.NullPointerException
at com.magicento.helpers.PsiPhpHelper.isPhp(PsiPhpHelper.java:95)
at com.magicento.helpers.MagentoParser.getUriType(MagentoParser.java:212)
at com.magicento.helpers.MagentoParser.isModelUri(MagentoParser.java:196)
at com.magicento.actions.SearchModelDataKeysAction.isApplicable(SearchModelDataKeysAction.java:33)
at com.magicento.MagicentoAction._getMagentoContextActions(MagicentoAction.java:95)
at com.magicento.MagicentoAction.executeAction(MagicentoAction.java:31)
at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:359)
at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:493)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by Schrank** [comment]
This only happens, if you are at the end of a file. I'm running on 131.374

**Comment by enriquepiatti** [comment]
Duplicate: https://github.com/enriquepiatti/Magicento/issues/84
This is fixed (but the bugfixed version was not release yet)

**Comment by Schrank** [comment]
Thanks! :-)

Am 05.11.13 20:22, schrieb Enrique Piatti:
