### ISSUE TITLE
Exception, when no variable is entered into Watches while debugging with xdebug?

### ISSUE THREAD

**Issue by Schrank** [enriquepiatti/Magicento#78]
I opened a new "variable-dialoge" (clicked the + in watches) and closed it immediatly because I clicked beside the dialoge - I repeated it a second time.

I think with the second try the exception was thrown.

```
null
java.lang.NullPointerException
    at com.magicento.helpers.MagentoParser.isObserverMethodInXml(MagentoParser.java:830)
    at com.magicento.extensions.MagicentoGotoDeclarationHandler.getGotoDeclarationTargets(MagicentoGotoDeclarationHandler.java:263)
    at com.magicento.extensions.MagicentoGotoDeclarationHandler.getGotoDeclarationTargets(MagicentoGotoDeclarationHandler.java:49)
    at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:208)
    at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findAllTargetElements(GotoDeclarationAction.java:193)
    at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.invoke(GotoDeclarationAction.java:82)
    at com.intellij.codeInsight.actions.CodeInsightAction$1$1.run(CodeInsightAction.java:63)
    at com.intellij.codeInsight.actions.CodeInsightAction$1.run(CodeInsightAction.java:70)
    at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:124)
    at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:99)
    at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:85)
    at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformedImpl(CodeInsightAction.java:55)
    at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformed(CodeInsightAction.java:41)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:476)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:332)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:544)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:55)
    at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:102)
    at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:679)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:507)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:332)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by enriquepiatti** [comment]
I'm not so sure if that was the reason, but anyway, it has a null check now so it will be fixed in the next release.
Thanks !
