### ISSUE TITLE
NoClassDefFound when editing xml file

### ISSUE THREAD

**Issue by thewunder** [enriquepiatti/Magicento#8]
phpstorm 5.01

org/apache/commons/collections/comparators/ComparableComparator: org/apache/commons/collections/comparators/ComparableComparator
java.lang.NoClassDefFoundError: org/apache/commons/collections/comparators/ComparableComparator
    at com.magicento.models.xml.MagentoXmlTag.getAllNodeNamesFromMergedXml(MagentoXmlTag.java:287)
    at com.magicento.models.xml.config.IdXmlTag.addAllNamesFrom(IdXmlTag.java:80)
    at com.magicento.models.xml.config.IdXmlTag.addAllEquivalentNames(IdXmlTag.java:69)
    at com.magicento.models.xml.config.system.TabsIdXmlTag.getPossibleNames(TabsIdXmlTag.java:15)
    at com.magicento.models.xml.MagentoXmlTag.getPossibleDefinitions(MagentoXmlTag.java:131)
    at com.magicento.models.xml.config.IdXmlTag.getPossibleDefinitions(IdXmlTag.java:40)
    at com.magicento.extensions.MagicentoXmlCompletionContributor$2.addCompletions(MagicentoXmlCompletionContributor.java:170)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:156)
    at com.magicento.extensions.MagicentoXmlCompletionContributor.fillCompletionVariants(MagicentoXmlCompletionContributor.java:235)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:110)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:103)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:90)
    at com.intellij.codeInsight.completion.XmlNoVariantsDelegator.fillCompletionVariants(XmlNoVariantsDelegator.java:26)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:83)
    at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:114)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$2$1$1.run(CodeCompletionHandlerBase.java:357)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:918)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$2$1.run(CodeCompletionHandlerBase.java:348)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:181)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:221)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:172)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$2.run(CodeCompletionHandlerBase.java:344)
    at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:457)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:148)

**Comment by enriquepiatti** [comment]
fixed in 0.8.2
