### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by Schrank** [enriquepiatti/Magicento#82]
Don't ask me what happend, just found it in the log.

```
null
java.lang.NullPointerException
    at com.magicento.helpers.MagentoParser.isObserverMethodInXml(MagentoParser.java:830)
    at com.magicento.extensions.MagicentoGotoDeclarationHandler.getGotoDeclarationTargets(MagicentoGotoDeclarationHandler.java:263)
    at com.magicento.extensions.MagicentoGotoDeclarationHandler.getGotoDeclarationTargets(MagicentoGotoDeclarationHandler.java:49)
    at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:206)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:495)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2100(CtrlMouseHandler.java:101)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:776)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2000(CtrlMouseHandler.java:723)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1$1.run(CtrlMouseHandler.java:766)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:948)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils$3.run(ProgressIndicatorUtils.java:62)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$8.run(ProgressManagerImpl.java:428)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:207)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:189)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:418)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:57)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.run(CtrlMouseHandler.java:763)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:434)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:151)
```

**Comment by enriquepiatti** [comment]
Already fixed (will be available soon, in the next release)
