### ISSUE TITLE
Opening Magicento menu in v2.4.0 creates NullPointerException on EAP 130.1639 (OSX)

### ISSUE THREAD

**Issue by jacobsenj** [enriquepiatti/Magicento#84]
Using PHPStorm 7 EAP 130.1639 and the latest Magicento 2.4.0 the following happens on opening the magicento menu (ALT+M)

![bildschirmfoto 2013-08-28 um 11 10 55](https://f.cloud.github.com/assets/399303/1040837/14b2ab86-0fc2-11e3-8980-220e39801f00.png)

![bildschirmfoto 2013-08-28 um 11 11 13](https://f.cloud.github.com/assets/399303/1040838/178bfc9a-0fc2-11e3-95ac-1e63c20659da.png)

--- snip ---
null
java.lang.NullPointerException
    at com.magicento.helpers.PsiPhpHelper.isPhp(PsiPhpHelper.java:95)
    at com.magicento.helpers.MagentoParser.getUriType(MagentoParser.java:212)
    at com.magicento.helpers.MagentoParser.isModelUri(MagentoParser.java:196)
    at com.magicento.actions.SearchModelDataKeysAction.isApplicable(SearchModelDataKeysAction.java:33)
    at com.magicento.MagicentoAction._getMagentoContextActions(MagicentoAction.java:95)
    at com.magicento.MagicentoAction.executeAction(MagicentoAction.java:31)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:359)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:476)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:332)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

java.lang.NullPointerException
    at com.magicento.helpers.PsiPhpHelper.isPhp(PsiPhpHelper.java:95)
    at com.magicento.helpers.MagentoParser.getUriType(MagentoParser.java:212)
    at com.magicento.helpers.MagentoParser.isModelUri(MagentoParser.java:196)
    at com.magicento.actions.SearchModelDataKeysAction.isApplicable(SearchModelDataKeysAction.java:33)
    at com.magicento.MagicentoAction._getMagentoContextActions(MagicentoAction.java:95)
    at com.magicento.MagicentoAction.executeAction(MagicentoAction.java:31)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:359)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:476)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:332)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

java.lang.NullPointerException
    at com.magicento.helpers.PsiPhpHelper.isPhp(PsiPhpHelper.java:95)
    at com.magicento.helpers.MagentoParser.getUriType(MagentoParser.java:212)
    at com.magicento.helpers.MagentoParser.isModelUri(MagentoParser.java:196)
    at com.magicento.actions.SearchModelDataKeysAction.isApplicable(SearchModelDataKeysAction.java:33)
    at com.magicento.MagicentoAction._getMagentoContextActions(MagicentoAction.java:95)
    at com.magicento.MagicentoAction.executeAction(MagicentoAction.java:31)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:359)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:476)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:332)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

java.lang.NullPointerException
    at com.magicento.helpers.PsiPhpHelper.isPhp(PsiPhpHelper.java:95)
    at com.magicento.helpers.MagentoParser.getUriType(MagentoParser.java:212)
    at com.magicento.helpers.MagentoParser.isModelUri(MagentoParser.java:196)
    at com.magicento.actions.SearchModelDataKeysAction.isApplicable(SearchModelDataKeysAction.java:33)
    at com.magicento.MagicentoAction._getMagentoContextActions(MagicentoAction.java:95)
    at com.magicento.MagicentoAction.executeAction(MagicentoAction.java:31)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:359)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:476)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:332)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

--- snap ---

**Comment by enriquepiatti** [comment]
Hi @jacobsenj I can't fix this at this moment because it is a EAP release, and hence the code from Jetbrains could change or has some bugs, please use the last stable release.

**Comment by jefsnare** [comment]
Hi @enriquepiatti I'm getting the same error in PHPStorm 6.03 with Magicento 2.4.0.

Error during dispatching of java.awt.event.KeyEvent[KEY_PRESSED,keyCode=77,keyText=M,keyChar='µ',modifiers=⌥,extModifiers=⌥,keyLocation=KEY_LOCATION_STANDARD,rawCode=0,primaryLevelUnicode=0,scancode=0] on frame2
java.lang.NullPointerException
    at com.magicento.helpers.PsiPhpHelper.isPhp(PsiPhpHelper.java:95)
    at com.magicento.helpers.MagentoParser.getUriType(MagentoParser.java:212)
    at com.magicento.helpers.MagentoParser.isModelUri(MagentoParser.java:196)
    at com.magicento.actions.SearchModelDataKeysAction.isApplicable(SearchModelDataKeysAction.java:33)
    at com.magicento.MagicentoAction._getMagentoContextActions(MagicentoAction.java:95)
    at com.magicento.MagicentoAction.executeAction(MagicentoAction.java:31)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:359)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:494)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by enriquepiatti** [comment]
OK, I've added a NullPointer check, but the weird thing is that it should not happen, is this happening always you try to use ALT+M? on any file? on any cursor position? on any project?

**Comment by jefsnare** [comment]
@enriquepiatti I just found out that when you do ALT+M at file ending (after a closing tag) than this error occurs. When I'm (for example) in the middle of the file, the Magicento menu is working fine. So it's only at file end, when this happens.

**Comment by enriquepiatti** [comment]
Yes that makes more sense. I will mark this as fixed, but the fix will be released with the other features for 2.5.0 because the workaround for this is just to not use ALT+M at the EOF (y)
