### ISSUE TITLE
ClassNotFoundException when working in layout.xml files

### ISSUE THREAD

**Issue by hnesk** [enriquepiatti/Magicento#87]
When I edit handles in layout.xml files an empty error message pops up (sometimes uncloseable, so I have to kill phpstorm). 
Hapeens on version 2.0.0 from the JetBrains Repository
Part of the Stacktrace:

```
...
java.lang.ClassNotFoundException: com.magicento.models.xml.config.AdminRoutersIdArgsFrontNameXmlTag PluginClassLoader[Magicento, 2.0.0]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:190)
    at com.magicento.helpers.JavaHelper.classExists(JavaHelper.java:21)
    at com.magicento.models.xml.MagentoXml._getClassNameFromTag(MagentoXml.java:170)
    at com.magicento.models.xml.MagentoXml._createChildren(MagentoXml.java:91)
    at com.magicento.models.xml.MagentoXml._createChildren(MagentoXml.java:111)
    at com.magicento.models.xml.MagentoXml._createChildren(MagentoXml.java:111)
    at com.magicento.models.xml.MagentoXml._createChildren(MagentoXml.java:111)
    at com.magicento.models.xml.MagentoXml._createChildren(MagentoXml.java:111)
    at com.magicento.models.xml.MagentoXml._create(MagentoXml.java:71)
    at com.magicento.models.xml.MagentoXml._init(MagentoXml.java:58)
    at com.magicento.models.xml.config.MagentoConfigXml._init(MagentoConfigXml.java:41)
    at com.magicento.models.xml.MagentoXml.<init>(MagentoXml.java:53)
    at com.magicento.models.xml.config.MagentoConfigXml.<init>(MagentoConfigXml.java:32)
    at com.magicento.models.xml.MagentoXmlFactory.getInstance(MagentoXmlFactory.java:56)
    at com.magicento.MagicentoProjectComponent.getCachedXml(MagicentoProjectComponent.java:173)
    at com.magicento.MagicentoProjectComponent.getCachedConfigXml(MagicentoProjectComponent.java:145)
    at com.magicento.models.xml.layout.MagentoLayoutXml.getAllActiveXmlLayoutNames(MagentoLayoutXml.java:127)
    at com.magicento.models.xml.layout.MagentoLayoutXml.getMergedXml(MagentoLayoutXml.java:98)
    at com.magicento.models.xml.MagentoXml.getMergedXmlFile(MagentoXml.java:267)
    at com.magicento.models.xml.MagentoXmlElement.getAllNodesFromMergedXml(MagentoXmlElement.java:261)
    at com.magicento.models.xml.MagentoXmlElement.getAllNodeNamesFromMergedXml(MagentoXmlElement.java:299)
    at com.magicento.models.xml.layout.HandleXmlTag.addAllNamesFrom(HandleXmlTag.java:99)
    at com.magicento.models.xml.layout.HandleXmlTag.addAllEquivalentNames(HandleXmlTag.java:88)
    at com.magicento.models.xml.layout.HandleXmlTag.getPossibleNames(HandleXmlTag.java:58)
    at com.magicento.models.xml.MagentoXmlTag.getPossibleDefinitions(MagentoXmlTag.java:116)
    at com.magicento.models.xml.layout.HandleXmlTag.getPossibleDefinitions(HandleXmlTag.java:68)
    at com.magicento.extensions.MagicentoXmlCompletionContributor$2.addCompletions(MagicentoXmlCompletionContributor.java:181)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:154)
    at com.magicento.extensions.MagicentoXmlCompletionContributor.fillCompletionVariants(MagicentoXmlCompletionContributor.java:325)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:117)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:110)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:97)
    at com.intellij.codeInsight.completion.XmlNoVariantsDelegator.fillCompletionVariants(XmlNoVariantsDelegator.java:26)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
    at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:115)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:775)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$900(CompletionProgressIndicator.java:86)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:757)
    at com.intellij.codeInsight.completion.AsyncCompletion$1$1$1.run(CompletionThreading.java:93)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:940)
    at com.intellij.codeInsight.completion.AsyncCompletion$1$1.run(CompletionThreading.java:88)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:185)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:226)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:175)
    at com.intellij.codeInsight.completion.AsyncCompletion$1.run(CompletionThreading.java:84)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:454)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:152)
...
```

**Comment by enriquepiatti** [comment]
Sorry @hnesk the code from that version is too old (2.0.0 from the repository is actually the same as 1.4.2), I'm not maintaining that version anymore.
