### ISSUE TITLE
Alt+m doesn't work

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#89]
```
Error during dispatching of java.awt.event.KeyEvent[KEY_PRESSED,keyCode=77,keyText=M,keyChar='m',modifiers=Alt,extModifiers=Alt,keyLocation=KEY_LOCATION_STANDARD,rawCode=77,primaryLevelUnicode=109,scancode=50,extendedKeyCode=0x4d] on frame0
java.lang.NullPointerException
    at com.magicento.helpers.PsiPhpHelper.isPhp(PsiPhpHelper.java:95)
    at com.magicento.helpers.MagentoParser.getUriType(MagentoParser.java:212)
    at com.magicento.helpers.MagentoParser.isModelUri(MagentoParser.java:196)
    at com.magicento.actions.SearchModelDataKeysAction.isApplicable(SearchModelDataKeysAction.java:33)
    at com.magicento.MagicentoAction._getMagentoContextActions(MagicentoAction.java:95)
    at com.magicento.MagicentoAction.executeAction(MagicentoAction.java:31)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:359)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:494)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

```

**Comment by enriquepiatti** [comment]
Please check if is the same issue here:
https://github.com/enriquepiatti/Magicento/issues/84

**Comment by Koc** [comment]
looks similar. I'm using 6.0.3 version
