### ISSUE TITLE
End config.xml of -> NullPointerException

### ISSUE THREAD

**Issue by Schrank** [enriquepiatti/Magicento#91]
Given:

```
<?xml version="1.0"?>
<config>
    <modules>
        <Namespace_Module>
            <version>1.0.0</version>
        </Namespace_Module>
    </modules>
    <global>
        <sales>
            <quote>
                <item>
                    <product_attributes>
                        <short_description />
                    </product_attributes>
                </item>
            </quote>
        </sales>
    </global>
</config>CURSOR HERE!
```

If I hit Alt + M I get a NullPointerException:

```
null
        java.lang.NullPointerException
        at com.magicento.helpers.PsiPhpHelper.isPhp(PsiPhpHelper.java:95)
        at com.magicento.helpers.MagentoParser.getUriType(MagentoParser.java:212)
        at com.magicento.helpers.MagentoParser.isModelUri(MagentoParser.java:196)
        at com.magicento.actions.SearchModelDataKeysAction.isApplicable(SearchModelDataKeysAction.java:33)
        at com.magicento.MagicentoAction._getMagentoContextActions(MagicentoAction.java:95)
        at com.magicento.MagicentoAction.executeAction(MagicentoAction.java:31)
        at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:359)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:493)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by enriquepiatti** [comment]
Thanks @Schrank, this is the same issue described here:
https://github.com/enriquepiatti/Magicento/issues/84
It is solved now, but I want to add more features before releasing a new version, and I think this bug is not so critical, you just need to avoid to use ALT+M at the end of the file.

**Comment by Schrank** [comment]
Thanks, oversaw it :(

Am 25.09.13 17:16, schrieb Enrique Piatti:

> Thanks @Schrank, this is the same issue described here:
> https://github.com/enriquepiatti/Magicento/issues/84
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/enriquepiatti/Magicento/issues/91#issuecomment-25095556

## 

Fabian Blechschmidt
Webentwicklung - Programmierung

Magento Certified Developer

Crailsheimer Str. 10
D - 12247 Berlin
Tel: +49 (0) 30 419 932 55
Handy: +49 (0)176 666 55 256
E-Mail: blechschmidt@fabian-blechschmidt.de
Web: www.fabian-blechschmidt.de
