### ISSUE TITLE
NullPointerException in phtml file 

### ISSUE THREAD

**Issue by Celldweller** [enriquepiatti/Magicento#94]
I get a reproducable error when using alt+m in a phtml file. It only occurs when the cursor is in a html area. When the cursor is placed inside a php block, no exception is thrown.

Versions: 
Magicento 2.4.0
PHPStorm 6.0.3
Mac OS 10.8.5

11:45:05 NullPointerException: Error during dispatching of java.awt.event.KeyEvent[KEY_PRESSED,keyCode=77,keyText=M,keyChar='µ',modifiers=⌥,extModifiers=⌥,keyLocation=KEY_LOCATION_STANDARD,rawCode=0,primaryLevelUnicode=0,scancode=0] on frame2
11:45:06 NullPointerException: Error during dispatching of java.awt.event.KeyEvent[KEY_PRESSED,keyCode=77,keyText=M,keyChar='µ',modifiers=⌥,extModifiers=⌥,keyLocation=KEY_LOCATION_STANDARD,rawCode=0,primaryLevelUnicode=0,scancode=0] on frame2
11:45:21 NullPointerException: Error during dispatching of java.awt.event.KeyEvent[KEY_PRESSED,keyCode=77,keyText=M,keyChar='µ',modifiers=⌥,extModifiers=⌥,keyLocation=KEY_LOCATION_STANDARD,rawCode=0,primaryLevelUnicode=0,scancode=0] on frame2

Hope it helps :-)

Greetings 
Celldweller

**Comment by enriquepiatti** [comment]
Hi @Celldweller, could you provide the full stack trace? (details tab)

**Comment by Celldweller** [comment]
Hi @enriquepiatti,

it seems it is the same error as #84 

Today I am only able to reproduce it when the cursor is on EOF like in #93 describend.

Full stack is as follows:

```
Error during dispatching of 
java.awt.event.KeyEvent[KEY_PRESSED,keyCode=77,keyText=M,keyChar='µ',modifiers=⌥,extModifiers=⌥,keyLocation=KEY_LOCATION_STANDARD,rawCode=0,primaryLevelUnicode=0,scancode=0] on frame2
java.lang.NullPointerException
    at com.magicento.helpers.PsiPhpHelper.isPhp(PsiPhpHelper.java:95)
    at com.magicento.helpers.MagentoParser.getUriType(MagentoParser.java:212)
    at com.magicento.helpers.MagentoParser.isModelUri(MagentoParser.java:196)
    at com.magicento.actions.SearchModelDataKeysAction.isApplicable(SearchModelDataKeysAction.java:33)
    at com.magicento.MagicentoAction._getMagentoContextActions(MagicentoAction.java:95)
    at com.magicento.MagicentoAction.executeAction(MagicentoAction.java:31)
    at com.magicento.actions.MagicentoActionAbstract.actionPerformed(MagicentoActionAbstract.java:359)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:494)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by enriquepiatti** [comment]
OK, then it will be solved on the next release (is solved now, but I'm finishing other features). Thanks !
