### ISSUE TITLE
Fatal error" is not legal for JDOM/XML elements: XML names cannot begin with the character

### ISSUE THREAD

**Issue by Schrank** [enriquepiatti/Magicento#99]
```
The name "
Fatal error" is not legal for JDOM/XML elements: XML names cannot begin with the character "
".: The name "
Fatal error" is not legal for JDOM/XML elements: XML names cannot begin with the character "
".
org.jdom.IllegalNameException: The name "
Fatal error" is not legal for JDOM/XML elements: XML names cannot begin with the character "
".
at org.jdom.Element.setName(Element.java:210)
at org.jdom.Element.<init>(Element.java:144)
    at org.jdom.Element.<init>(Element.java:156)
        at com.magicento.models.VarienObjectData.saveDataKeys(VarienObjectData.java:97)
        at com.magicento.models.VarienObjectData$1.doSomethingWithResult(VarienObjectData.java:162)
        at com.magicento.helpers.PHP.executeVisitor(PHP.java:124)
        at com.magicento.helpers.PHP.executeWithCommandLine(PHP.java:116)
        at com.magicento.helpers.PHP.execute(PHP.java:63)
        at com.magicento.MagicentoProjectComponent.executePhpWithMagento(MagicentoProjectComponent.java:343)
        at com.magicento.models.VarienObjectData.saveDataKeys(VarienObjectData.java:153)
        at com.magicento.extensions.MagicentoPhpCompletionContributor$1.handleInsert(MagicentoPhpCompletionContributor.java:49)
        at com.intellij.codeInsight.lookup.LookupElementBuilder.handleInsert(LookupElementBuilder.java:321)
        at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$8.run(CodeCompletionHandlerBase.java:707)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1020)
        at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.a(CodeCompletionHandlerBase.java:697)
        at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.a(CodeCompletionHandlerBase.java:630)
        at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lookupItemSelected(CodeCompletionHandlerBase.java:573)
        at com.intellij.codeInsight.completion.CompletionProgressIndicator$2.itemSelected(CompletionProgressIndicator.java:110)
        at com.intellij.codeInsight.lookup.impl.LookupImpl.fireItemSelected(LookupImpl.java:1009)
        at com.intellij.codeInsight.lookup.impl.LookupImpl.finishLookup(LookupImpl.java:649)
        at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$3.run(CodeCompletionHandlerBase.java:424)
        at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:124)
        at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:99)
        at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:85)
        at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.completionFinished(CodeCompletionHandlerBase.java:420)
        at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.a(CodeCompletionHandlerBase.java:308)
        at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.a(CodeCompletionHandlerBase.java:513)
        at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.invokeCompletion(CodeCompletionHandlerBase.java:186)
        at com.intellij.codeInsight.completion.actions.BaseCodeCompletionAction.invokeCompletion(BaseCodeCompletionAction.java:50)
        at com.intellij.codeInsight.completion.actions.CodeCompletionAction.actionPerformed(CodeCompletionAction.java:32)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:493)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by enriquepiatti** [comment]
Hi @Schrank this is already solved (will be available on the next release), but momentary are you sure the eval.php is correctly executed? please check your Magicento settings for the PHP section, you have more details there to test the eval.php
If you are using the http option, you can even debug the eval.php, just look for eval.php in PhpStorm, put a breakpoint there, and try to access to that file with your browser (using your webserver of course not the physical path).
Also could you provide more details about what are you doing to reproduce that error? (I'm assuming you are using something like ->get[CTRL+SPACE] and then selecting "SEARCH_VARIEN_OBJECT_KEYS_TEXT". If that is the case are you using something like $this->get[CTRL+SPACE] or Mage::getModel('...')->get[CTRL+SPACE] ?

**Comment by Schrank** [comment]
I'm very sorry. I have no idea what I did, but I'll report back when I know more.
